// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

module AESL_axi_slave_AXILiteS (
    clk,
    reset,
    TRAN_s_axi_AXILiteS_AWADDR,
    TRAN_s_axi_AXILiteS_AWVALID,
    TRAN_s_axi_AXILiteS_AWREADY,
    TRAN_s_axi_AXILiteS_WVALID,
    TRAN_s_axi_AXILiteS_WREADY,
    TRAN_s_axi_AXILiteS_WDATA,
    TRAN_s_axi_AXILiteS_WSTRB,
    TRAN_s_axi_AXILiteS_ARADDR,
    TRAN_s_axi_AXILiteS_ARVALID,
    TRAN_s_axi_AXILiteS_ARREADY,
    TRAN_s_axi_AXILiteS_RVALID,
    TRAN_s_axi_AXILiteS_RREADY,
    TRAN_s_axi_AXILiteS_RDATA,
    TRAN_s_axi_AXILiteS_RRESP,
    TRAN_s_axi_AXILiteS_BVALID,
    TRAN_s_axi_AXILiteS_BREADY,
    TRAN_s_axi_AXILiteS_BRESP,
    TRAN_AXILiteS_write_data_finish,
    TRAN_AXILiteS_read_data_finish,
    TRAN_AXILiteS_start_in,
    TRAN_AXILiteS_idle_out,
    TRAN_AXILiteS_ready_out,
    TRAN_AXILiteS_ready_in,
    TRAN_AXILiteS_done_out,
    TRAN_AXILiteS_write_start_in   ,
    TRAN_AXILiteS_write_start_finish,
    TRAN_AXILiteS_interrupt,
    TRAN_AXILiteS_transaction_done_in
    );

//------------------------Parameter----------------------
`define TV_IN_reset_A_V "../tv/cdatafile/c.Decision.autotvin_reset_A_V.dat"
`define TV_IN_reset_V_V "../tv/cdatafile/c.Decision.autotvin_reset_V_V.dat"
`define TV_IN_reset_params_V "../tv/cdatafile/c.Decision.autotvin_reset_params_V.dat"
`define TV_IN_athresh "../tv/cdatafile/c.Decision.autotvin_athresh.dat"
`define TV_IN_vthresh "../tv/cdatafile/c.Decision.autotvin_vthresh.dat"
`define TV_IN_a_flip "../tv/cdatafile/c.Decision.autotvin_a_flip.dat"
`define TV_IN_v_flip "../tv/cdatafile/c.Decision.autotvin_v_flip.dat"
`define TV_IN_a_length "../tv/cdatafile/c.Decision.autotvin_a_length.dat"
`define TV_IN_v_length "../tv/cdatafile/c.Decision.autotvin_v_length.dat"
`define TV_IN_data "../tv/cdatafile/c.Decision.autotvin_data.dat"
`define TV_OUT_ap_return "../tv/rtldatafile/rtl.Decision.autotvout_ap_return.dat"
parameter ADDR_WIDTH = 7;
parameter DATA_WIDTH = 32;
parameter reset_A_V_DEPTH = 1;
reg [31 : 0] reset_A_V_OPERATE_DEPTH = 0;
parameter reset_A_V_c_bitwidth = 1;
parameter reset_V_V_DEPTH = 1;
reg [31 : 0] reset_V_V_OPERATE_DEPTH = 0;
parameter reset_V_V_c_bitwidth = 1;
parameter reset_params_V_DEPTH = 1;
reg [31 : 0] reset_params_V_OPERATE_DEPTH = 0;
parameter reset_params_V_c_bitwidth = 1;
parameter athresh_DEPTH = 1;
reg [31 : 0] athresh_OPERATE_DEPTH = 0;
parameter athresh_c_bitwidth = 32;
parameter vthresh_DEPTH = 1;
reg [31 : 0] vthresh_OPERATE_DEPTH = 0;
parameter vthresh_c_bitwidth = 32;
parameter a_flip_DEPTH = 1;
reg [31 : 0] a_flip_OPERATE_DEPTH = 0;
parameter a_flip_c_bitwidth = 8;
parameter v_flip_DEPTH = 1;
reg [31 : 0] v_flip_OPERATE_DEPTH = 0;
parameter v_flip_c_bitwidth = 8;
parameter a_length_DEPTH = 1;
reg [31 : 0] a_length_OPERATE_DEPTH = 0;
parameter a_length_c_bitwidth = 32;
parameter v_length_DEPTH = 1;
reg [31 : 0] v_length_OPERATE_DEPTH = 0;
parameter v_length_c_bitwidth = 32;
parameter data_DEPTH = 1;
reg [31 : 0] data_OPERATE_DEPTH = 0;
parameter data_c_bitwidth = 16;
parameter ap_return_DEPTH = 1;
reg [31 : 0] ap_return_OPERATE_DEPTH = 0;
parameter ap_return_c_bitwidth = 16;
parameter START_ADDR = 0;
parameter Decision_continue_addr = 0;
parameter Decision_auto_start_addr = 0;
parameter reset_A_V_data_in_addr = 24;
parameter reset_V_V_data_in_addr = 32;
parameter reset_params_V_data_in_addr = 40;
parameter athresh_data_in_addr = 48;
parameter vthresh_data_in_addr = 56;
parameter a_flip_data_in_addr = 64;
parameter v_flip_data_in_addr = 72;
parameter a_length_data_in_addr = 80;
parameter v_length_data_in_addr = 88;
parameter data_data_in_addr = 96;
parameter ap_return_data_out_addr = 16;
parameter STATUS_ADDR = 0;

output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_AXILiteS_AWADDR;
output  TRAN_s_axi_AXILiteS_AWVALID;
input  TRAN_s_axi_AXILiteS_AWREADY;
output  TRAN_s_axi_AXILiteS_WVALID;
input  TRAN_s_axi_AXILiteS_WREADY;
output [DATA_WIDTH - 1 : 0] TRAN_s_axi_AXILiteS_WDATA;
output [DATA_WIDTH/8 - 1 : 0] TRAN_s_axi_AXILiteS_WSTRB;
output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_AXILiteS_ARADDR;
output  TRAN_s_axi_AXILiteS_ARVALID;
input  TRAN_s_axi_AXILiteS_ARREADY;
input  TRAN_s_axi_AXILiteS_RVALID;
output  TRAN_s_axi_AXILiteS_RREADY;
input [DATA_WIDTH - 1 : 0] TRAN_s_axi_AXILiteS_RDATA;
input [2 - 1 : 0] TRAN_s_axi_AXILiteS_RRESP;
input  TRAN_s_axi_AXILiteS_BVALID;
output  TRAN_s_axi_AXILiteS_BREADY;
input [2 - 1 : 0] TRAN_s_axi_AXILiteS_BRESP;
output TRAN_AXILiteS_write_data_finish;
output TRAN_AXILiteS_read_data_finish;
input     clk;
input     reset;
input     TRAN_AXILiteS_start_in;
output    TRAN_AXILiteS_done_out;
output    TRAN_AXILiteS_ready_out;
input     TRAN_AXILiteS_ready_in;
output    TRAN_AXILiteS_idle_out;
input  TRAN_AXILiteS_write_start_in   ;
output TRAN_AXILiteS_write_start_finish;
input     TRAN_AXILiteS_interrupt;
input     TRAN_AXILiteS_transaction_done_in;

reg [ADDR_WIDTH - 1 : 0] AWADDR_reg = 0;
reg  AWVALID_reg = 0;
reg  WVALID_reg = 0;
reg [DATA_WIDTH - 1 : 0] WDATA_reg = 0;
reg [DATA_WIDTH/8 - 1 : 0] WSTRB_reg = 0;
reg [ADDR_WIDTH - 1 : 0] ARADDR_reg = 0;
reg  ARVALID_reg = 0;
reg  RREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] RDATA_reg = 0;
reg  BREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] mem_reset_A_V [reset_A_V_DEPTH - 1 : 0];
reg reset_A_V_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_reset_V_V [reset_V_V_DEPTH - 1 : 0];
reg reset_V_V_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_reset_params_V [reset_params_V_DEPTH - 1 : 0];
reg reset_params_V_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_athresh [athresh_DEPTH - 1 : 0];
reg athresh_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_vthresh [vthresh_DEPTH - 1 : 0];
reg vthresh_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_a_flip [a_flip_DEPTH - 1 : 0];
reg a_flip_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_v_flip [v_flip_DEPTH - 1 : 0];
reg v_flip_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_a_length [a_length_DEPTH - 1 : 0];
reg a_length_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_v_length [v_length_DEPTH - 1 : 0];
reg v_length_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_data [data_DEPTH - 1 : 0];
reg data_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_ap_return [ap_return_DEPTH - 1 : 0];
reg ap_return_read_data_finish;
reg AESL_ready_out_index_reg = 0;
reg AESL_write_start_finish = 0;
reg AESL_ready_reg;
reg ready_initial;
reg AESL_done_index_reg = 0;
reg AESL_idle_index_reg = 0;
reg AESL_auto_restart_index_reg;
reg process_0_finish = 0;
reg process_1_finish = 0;
reg process_2_finish = 0;
reg process_3_finish = 0;
reg process_4_finish = 0;
reg process_5_finish = 0;
reg process_6_finish = 0;
reg process_7_finish = 0;
reg process_8_finish = 0;
reg process_9_finish = 0;
reg process_10_finish = 0;
reg process_11_finish = 0;
reg process_12_finish = 0;
//write reset_A_V reg
reg [31 : 0] write_reset_A_V_count = 0;
reg write_reset_A_V_run_flag = 0;
reg write_one_reset_A_V_data_done = 0;
//write reset_V_V reg
reg [31 : 0] write_reset_V_V_count = 0;
reg write_reset_V_V_run_flag = 0;
reg write_one_reset_V_V_data_done = 0;
//write reset_params_V reg
reg [31 : 0] write_reset_params_V_count = 0;
reg write_reset_params_V_run_flag = 0;
reg write_one_reset_params_V_data_done = 0;
//write athresh reg
reg [31 : 0] write_athresh_count = 0;
reg write_athresh_run_flag = 0;
reg write_one_athresh_data_done = 0;
//write vthresh reg
reg [31 : 0] write_vthresh_count = 0;
reg write_vthresh_run_flag = 0;
reg write_one_vthresh_data_done = 0;
//write a_flip reg
reg [31 : 0] write_a_flip_count = 0;
reg write_a_flip_run_flag = 0;
reg write_one_a_flip_data_done = 0;
//write v_flip reg
reg [31 : 0] write_v_flip_count = 0;
reg write_v_flip_run_flag = 0;
reg write_one_v_flip_data_done = 0;
//write a_length reg
reg [31 : 0] write_a_length_count = 0;
reg write_a_length_run_flag = 0;
reg write_one_a_length_data_done = 0;
//write v_length reg
reg [31 : 0] write_v_length_count = 0;
reg write_v_length_run_flag = 0;
reg write_one_v_length_data_done = 0;
//write data reg
reg [31 : 0] write_data_count = 0;
reg write_data_run_flag = 0;
reg write_one_data_data_done = 0;
//read ap_return reg
reg [31 : 0] read_ap_return_count = 0;
reg read_ap_return_run_flag = 0;
reg read_one_ap_return_data_done = 0;
reg [31 : 0] write_start_count = 0;
reg write_start_run_flag = 0;

//===================process control=================
reg [31 : 0] ongoing_process_number = 0;
//process number depends on how much processes needed.
reg process_busy = 0;

//=================== signal connection ==============
assign TRAN_s_axi_AXILiteS_AWADDR = AWADDR_reg;
assign TRAN_s_axi_AXILiteS_AWVALID = AWVALID_reg;
assign TRAN_s_axi_AXILiteS_WVALID = WVALID_reg;
assign TRAN_s_axi_AXILiteS_WDATA = WDATA_reg;
assign TRAN_s_axi_AXILiteS_WSTRB = WSTRB_reg;
assign TRAN_s_axi_AXILiteS_ARADDR = ARADDR_reg;
assign TRAN_s_axi_AXILiteS_ARVALID = ARVALID_reg;
assign TRAN_s_axi_AXILiteS_RREADY = RREADY_reg;
assign TRAN_s_axi_AXILiteS_BREADY = BREADY_reg;
assign TRAN_AXILiteS_write_start_finish = AESL_write_start_finish;
assign TRAN_AXILiteS_done_out = AESL_done_index_reg;
assign TRAN_AXILiteS_ready_out = AESL_ready_out_index_reg;
assign TRAN_AXILiteS_idle_out = AESL_idle_index_reg;
assign TRAN_AXILiteS_read_data_finish = 1 & ap_return_read_data_finish;
assign TRAN_AXILiteS_write_data_finish = 1 & reset_A_V_write_data_finish & reset_V_V_write_data_finish & reset_params_V_write_data_finish & athresh_write_data_finish & vthresh_write_data_finish & a_flip_write_data_finish & v_flip_write_data_finish & a_length_write_data_finish & v_length_write_data_finish & data_write_data_finish;
always @(TRAN_AXILiteS_ready_in or ready_initial) 
begin
    AESL_ready_reg <= TRAN_AXILiteS_ready_in | ready_initial;
end

always @(reset or process_0_finish or process_1_finish or process_2_finish or process_3_finish or process_4_finish or process_5_finish or process_6_finish or process_7_finish or process_8_finish or process_9_finish or process_10_finish or process_11_finish or process_12_finish ) begin
    if (reset == 0) begin
        ongoing_process_number <= 0;
    end
    else if (ongoing_process_number == 0 && process_0_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 1 && process_1_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 2 && process_2_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 3 && process_3_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 4 && process_4_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 5 && process_5_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 6 && process_6_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 7 && process_7_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 8 && process_8_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 9 && process_9_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 10 && process_10_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 11 && process_11_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 12 && process_12_finish == 1) begin
            ongoing_process_number <= 0;
    end
end

task count_c_data_four_byte_num_by_bitwidth;
input  integer bitwidth;
output integer num;
integer factor;
integer i;
begin
    factor = 32;
    for (i = 1; i <= 32; i = i + 1) begin
        if (bitwidth <= factor && bitwidth > factor - 32) begin
            num = i;
        end
        factor = factor + 32;
    end
end    
endtask

task count_seperate_factor_by_bitwidth;
input  integer bitwidth;
output integer factor;
begin
    if (bitwidth <= 8 ) begin
        factor=4;
    end
    if (bitwidth <= 16 & bitwidth > 8 ) begin
        factor=2;
    end
    if (bitwidth <= 32 & bitwidth > 16 ) begin
        factor=1;
    end
    if (bitwidth <= 1024 & bitwidth > 32 ) begin
        factor=1;
    end
end    
endtask

task count_operate_depth_by_bitwidth_and_depth;
input  integer bitwidth;
input  integer depth;
output integer operate_depth;
integer factor;
integer remain;
begin
    count_seperate_factor_by_bitwidth (bitwidth , factor);
    operate_depth = depth / factor;
    remain = depth % factor;
    if (remain > 0) begin
        operate_depth = operate_depth + 1;
    end
end    
endtask

task write; /*{{{*/
    input  reg [ADDR_WIDTH - 1:0] waddr;   // write address
    input  reg [DATA_WIDTH - 1:0] wdata;   // write data
    output reg wresp;
    reg aw_flag;
    reg w_flag;
    reg [DATA_WIDTH/8 - 1:0] wstrb_reg;
    integer i;
begin 
    wresp = 0;
    aw_flag = 0;
    w_flag = 0;
//=======================one single write operate======================
    AWADDR_reg <= waddr;
    AWVALID_reg <= 1;
    WDATA_reg <= wdata;
    WVALID_reg <= 1;
    for (i = 0; i < DATA_WIDTH/8; i = i + 1) begin
        wstrb_reg [i] = 1;
    end    
    WSTRB_reg <= wstrb_reg;
    while (!(aw_flag && w_flag)) begin
        @(posedge clk);
        if (aw_flag != 1)
            aw_flag = TRAN_s_axi_AXILiteS_AWREADY & AWVALID_reg;
        if (w_flag != 1)
            w_flag = TRAN_s_axi_AXILiteS_WREADY & WVALID_reg;
        AWVALID_reg <= !aw_flag;
        WVALID_reg <= !w_flag;
    end

    BREADY_reg <= 1;
    while (TRAN_s_axi_AXILiteS_BVALID != 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    BREADY_reg <= 0;
    if (TRAN_s_axi_AXILiteS_BRESP === 2'b00) begin
        wresp = 1;
        //input success. in fact BRESP is always 2'b00
    end   
//=======================one single write operate======================

end
endtask/*}}}*/

task read (/*{{{*/
    input  [ADDR_WIDTH - 1:0] raddr ,   // write address
    output [DATA_WIDTH - 1:0] RDATA_result ,
    output rresp
);
begin 
    rresp = 0;
//=======================one single read operate======================
    ARADDR_reg <= raddr;
    ARVALID_reg <= 1;
    while (TRAN_s_axi_AXILiteS_ARREADY !== 1) begin
        @(posedge clk);
    end
    @(posedge clk);
    ARVALID_reg <= 0;
    RREADY_reg <= 1;
    while (TRAN_s_axi_AXILiteS_RVALID !== 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    RDATA_result  <= TRAN_s_axi_AXILiteS_RDATA;
    RREADY_reg <= 0;
    if (TRAN_s_axi_AXILiteS_RRESP === 2'b00 ) begin
        rresp <= 1;
        //output success. in fact RRESP is always 2'b00
    end  
    @(posedge clk);

//=======================one single read operate end======================

end
endtask/*}}}*/

initial begin : ready_initial_process
    ready_initial = 0;
    wait(reset === 1);
    @(posedge clk);
    ready_initial = 1;
    @(posedge clk);
    ready_initial = 0;
end

initial begin : update_status
    integer process_num ;
    integer read_status_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 0;
    while (1) begin
        process_0_finish = 0;
        AESL_done_index_reg         <= 0;
        AESL_ready_out_index_reg        <= 0;
        if (ongoing_process_number === process_num && process_busy === 0) begin
            process_busy = 1;
            read (STATUS_ADDR, RDATA_reg, read_status_resp);
                AESL_done_index_reg         <= RDATA_reg[1 : 1];
                AESL_ready_out_index_reg    <= RDATA_reg[1 : 1];
                AESL_idle_index_reg         <= RDATA_reg[2 : 2];
            process_0_finish = 1;
            process_busy = 0;
        end 
        @(posedge clk);
    end
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        reset_A_V_write_data_finish <= 0;
        write_reset_A_V_run_flag <= 0; 
        write_reset_A_V_count = 0;
        count_operate_depth_by_bitwidth_and_depth (reset_A_V_c_bitwidth, reset_A_V_DEPTH, reset_A_V_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            reset_A_V_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_reset_A_V_run_flag <= 1; 
            write_reset_A_V_count = 0;
        end
        if (write_one_reset_A_V_data_done === 1) begin
            write_reset_A_V_count = write_reset_A_V_count + 1;
            if (write_reset_A_V_count == reset_A_V_OPERATE_DEPTH) begin
                write_reset_A_V_run_flag <= 0; 
                reset_A_V_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_reset_A_V
    integer write_reset_A_V_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] reset_A_V_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = reset_A_V_c_bitwidth;
    process_num = 1;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_1_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_reset_A_V_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write reset_A_V data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (reset_A_V_c_bitwidth < 32) begin
                        reset_A_V_data_tmp_reg = mem_reset_A_V[write_reset_A_V_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < reset_A_V_c_bitwidth) begin
                                reset_A_V_data_tmp_reg[j] = mem_reset_A_V[write_reset_A_V_count][i*32 + j];
                            end
                            else begin
                                reset_A_V_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (reset_A_V_data_in_addr + write_reset_A_V_count * four_byte_num * 4 + i * 4, reset_A_V_data_tmp_reg, write_reset_A_V_resp);
                end
                process_busy = 0;
                write_one_reset_A_V_data_done <= 1;
                @(posedge clk);
                write_one_reset_A_V_data_done <= 0;
            end   
            process_1_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        reset_V_V_write_data_finish <= 0;
        write_reset_V_V_run_flag <= 0; 
        write_reset_V_V_count = 0;
        count_operate_depth_by_bitwidth_and_depth (reset_V_V_c_bitwidth, reset_V_V_DEPTH, reset_V_V_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            reset_V_V_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_reset_V_V_run_flag <= 1; 
            write_reset_V_V_count = 0;
        end
        if (write_one_reset_V_V_data_done === 1) begin
            write_reset_V_V_count = write_reset_V_V_count + 1;
            if (write_reset_V_V_count == reset_V_V_OPERATE_DEPTH) begin
                write_reset_V_V_run_flag <= 0; 
                reset_V_V_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_reset_V_V
    integer write_reset_V_V_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] reset_V_V_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = reset_V_V_c_bitwidth;
    process_num = 2;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_2_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_reset_V_V_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write reset_V_V data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (reset_V_V_c_bitwidth < 32) begin
                        reset_V_V_data_tmp_reg = mem_reset_V_V[write_reset_V_V_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < reset_V_V_c_bitwidth) begin
                                reset_V_V_data_tmp_reg[j] = mem_reset_V_V[write_reset_V_V_count][i*32 + j];
                            end
                            else begin
                                reset_V_V_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (reset_V_V_data_in_addr + write_reset_V_V_count * four_byte_num * 4 + i * 4, reset_V_V_data_tmp_reg, write_reset_V_V_resp);
                end
                process_busy = 0;
                write_one_reset_V_V_data_done <= 1;
                @(posedge clk);
                write_one_reset_V_V_data_done <= 0;
            end   
            process_2_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        reset_params_V_write_data_finish <= 0;
        write_reset_params_V_run_flag <= 0; 
        write_reset_params_V_count = 0;
        count_operate_depth_by_bitwidth_and_depth (reset_params_V_c_bitwidth, reset_params_V_DEPTH, reset_params_V_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            reset_params_V_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_reset_params_V_run_flag <= 1; 
            write_reset_params_V_count = 0;
        end
        if (write_one_reset_params_V_data_done === 1) begin
            write_reset_params_V_count = write_reset_params_V_count + 1;
            if (write_reset_params_V_count == reset_params_V_OPERATE_DEPTH) begin
                write_reset_params_V_run_flag <= 0; 
                reset_params_V_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_reset_params_V
    integer write_reset_params_V_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] reset_params_V_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = reset_params_V_c_bitwidth;
    process_num = 3;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_3_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_reset_params_V_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write reset_params_V data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (reset_params_V_c_bitwidth < 32) begin
                        reset_params_V_data_tmp_reg = mem_reset_params_V[write_reset_params_V_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < reset_params_V_c_bitwidth) begin
                                reset_params_V_data_tmp_reg[j] = mem_reset_params_V[write_reset_params_V_count][i*32 + j];
                            end
                            else begin
                                reset_params_V_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (reset_params_V_data_in_addr + write_reset_params_V_count * four_byte_num * 4 + i * 4, reset_params_V_data_tmp_reg, write_reset_params_V_resp);
                end
                process_busy = 0;
                write_one_reset_params_V_data_done <= 1;
                @(posedge clk);
                write_one_reset_params_V_data_done <= 0;
            end   
            process_3_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        athresh_write_data_finish <= 0;
        write_athresh_run_flag <= 0; 
        write_athresh_count = 0;
        count_operate_depth_by_bitwidth_and_depth (athresh_c_bitwidth, athresh_DEPTH, athresh_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            athresh_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_athresh_run_flag <= 1; 
            write_athresh_count = 0;
        end
        if (write_one_athresh_data_done === 1) begin
            write_athresh_count = write_athresh_count + 1;
            if (write_athresh_count == athresh_OPERATE_DEPTH) begin
                write_athresh_run_flag <= 0; 
                athresh_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_athresh
    integer write_athresh_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] athresh_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = athresh_c_bitwidth;
    process_num = 4;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_4_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_athresh_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write athresh data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (athresh_c_bitwidth < 32) begin
                        athresh_data_tmp_reg = mem_athresh[write_athresh_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < athresh_c_bitwidth) begin
                                athresh_data_tmp_reg[j] = mem_athresh[write_athresh_count][i*32 + j];
                            end
                            else begin
                                athresh_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (athresh_data_in_addr + write_athresh_count * four_byte_num * 4 + i * 4, athresh_data_tmp_reg, write_athresh_resp);
                end
                process_busy = 0;
                write_one_athresh_data_done <= 1;
                @(posedge clk);
                write_one_athresh_data_done <= 0;
            end   
            process_4_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        vthresh_write_data_finish <= 0;
        write_vthresh_run_flag <= 0; 
        write_vthresh_count = 0;
        count_operate_depth_by_bitwidth_and_depth (vthresh_c_bitwidth, vthresh_DEPTH, vthresh_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            vthresh_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_vthresh_run_flag <= 1; 
            write_vthresh_count = 0;
        end
        if (write_one_vthresh_data_done === 1) begin
            write_vthresh_count = write_vthresh_count + 1;
            if (write_vthresh_count == vthresh_OPERATE_DEPTH) begin
                write_vthresh_run_flag <= 0; 
                vthresh_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_vthresh
    integer write_vthresh_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] vthresh_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = vthresh_c_bitwidth;
    process_num = 5;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_5_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_vthresh_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write vthresh data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (vthresh_c_bitwidth < 32) begin
                        vthresh_data_tmp_reg = mem_vthresh[write_vthresh_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < vthresh_c_bitwidth) begin
                                vthresh_data_tmp_reg[j] = mem_vthresh[write_vthresh_count][i*32 + j];
                            end
                            else begin
                                vthresh_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (vthresh_data_in_addr + write_vthresh_count * four_byte_num * 4 + i * 4, vthresh_data_tmp_reg, write_vthresh_resp);
                end
                process_busy = 0;
                write_one_vthresh_data_done <= 1;
                @(posedge clk);
                write_one_vthresh_data_done <= 0;
            end   
            process_5_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        a_flip_write_data_finish <= 0;
        write_a_flip_run_flag <= 0; 
        write_a_flip_count = 0;
        count_operate_depth_by_bitwidth_and_depth (a_flip_c_bitwidth, a_flip_DEPTH, a_flip_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            a_flip_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_a_flip_run_flag <= 1; 
            write_a_flip_count = 0;
        end
        if (write_one_a_flip_data_done === 1) begin
            write_a_flip_count = write_a_flip_count + 1;
            if (write_a_flip_count == a_flip_OPERATE_DEPTH) begin
                write_a_flip_run_flag <= 0; 
                a_flip_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_a_flip
    integer write_a_flip_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] a_flip_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = a_flip_c_bitwidth;
    process_num = 6;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_6_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_a_flip_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write a_flip data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (a_flip_c_bitwidth < 32) begin
                        a_flip_data_tmp_reg = mem_a_flip[write_a_flip_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < a_flip_c_bitwidth) begin
                                a_flip_data_tmp_reg[j] = mem_a_flip[write_a_flip_count][i*32 + j];
                            end
                            else begin
                                a_flip_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (a_flip_data_in_addr + write_a_flip_count * four_byte_num * 4 + i * 4, a_flip_data_tmp_reg, write_a_flip_resp);
                end
                process_busy = 0;
                write_one_a_flip_data_done <= 1;
                @(posedge clk);
                write_one_a_flip_data_done <= 0;
            end   
            process_6_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        v_flip_write_data_finish <= 0;
        write_v_flip_run_flag <= 0; 
        write_v_flip_count = 0;
        count_operate_depth_by_bitwidth_and_depth (v_flip_c_bitwidth, v_flip_DEPTH, v_flip_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            v_flip_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_v_flip_run_flag <= 1; 
            write_v_flip_count = 0;
        end
        if (write_one_v_flip_data_done === 1) begin
            write_v_flip_count = write_v_flip_count + 1;
            if (write_v_flip_count == v_flip_OPERATE_DEPTH) begin
                write_v_flip_run_flag <= 0; 
                v_flip_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_v_flip
    integer write_v_flip_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] v_flip_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = v_flip_c_bitwidth;
    process_num = 7;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_7_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_v_flip_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write v_flip data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (v_flip_c_bitwidth < 32) begin
                        v_flip_data_tmp_reg = mem_v_flip[write_v_flip_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < v_flip_c_bitwidth) begin
                                v_flip_data_tmp_reg[j] = mem_v_flip[write_v_flip_count][i*32 + j];
                            end
                            else begin
                                v_flip_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (v_flip_data_in_addr + write_v_flip_count * four_byte_num * 4 + i * 4, v_flip_data_tmp_reg, write_v_flip_resp);
                end
                process_busy = 0;
                write_one_v_flip_data_done <= 1;
                @(posedge clk);
                write_one_v_flip_data_done <= 0;
            end   
            process_7_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        a_length_write_data_finish <= 0;
        write_a_length_run_flag <= 0; 
        write_a_length_count = 0;
        count_operate_depth_by_bitwidth_and_depth (a_length_c_bitwidth, a_length_DEPTH, a_length_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            a_length_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_a_length_run_flag <= 1; 
            write_a_length_count = 0;
        end
        if (write_one_a_length_data_done === 1) begin
            write_a_length_count = write_a_length_count + 1;
            if (write_a_length_count == a_length_OPERATE_DEPTH) begin
                write_a_length_run_flag <= 0; 
                a_length_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_a_length
    integer write_a_length_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] a_length_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = a_length_c_bitwidth;
    process_num = 8;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_8_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_a_length_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write a_length data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (a_length_c_bitwidth < 32) begin
                        a_length_data_tmp_reg = mem_a_length[write_a_length_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < a_length_c_bitwidth) begin
                                a_length_data_tmp_reg[j] = mem_a_length[write_a_length_count][i*32 + j];
                            end
                            else begin
                                a_length_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (a_length_data_in_addr + write_a_length_count * four_byte_num * 4 + i * 4, a_length_data_tmp_reg, write_a_length_resp);
                end
                process_busy = 0;
                write_one_a_length_data_done <= 1;
                @(posedge clk);
                write_one_a_length_data_done <= 0;
            end   
            process_8_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        v_length_write_data_finish <= 0;
        write_v_length_run_flag <= 0; 
        write_v_length_count = 0;
        count_operate_depth_by_bitwidth_and_depth (v_length_c_bitwidth, v_length_DEPTH, v_length_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            v_length_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_v_length_run_flag <= 1; 
            write_v_length_count = 0;
        end
        if (write_one_v_length_data_done === 1) begin
            write_v_length_count = write_v_length_count + 1;
            if (write_v_length_count == v_length_OPERATE_DEPTH) begin
                write_v_length_run_flag <= 0; 
                v_length_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_v_length
    integer write_v_length_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] v_length_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = v_length_c_bitwidth;
    process_num = 9;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_9_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_v_length_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write v_length data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (v_length_c_bitwidth < 32) begin
                        v_length_data_tmp_reg = mem_v_length[write_v_length_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < v_length_c_bitwidth) begin
                                v_length_data_tmp_reg[j] = mem_v_length[write_v_length_count][i*32 + j];
                            end
                            else begin
                                v_length_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (v_length_data_in_addr + write_v_length_count * four_byte_num * 4 + i * 4, v_length_data_tmp_reg, write_v_length_resp);
                end
                process_busy = 0;
                write_one_v_length_data_done <= 1;
                @(posedge clk);
                write_one_v_length_data_done <= 0;
            end   
            process_9_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        data_write_data_finish <= 0;
        write_data_run_flag <= 0; 
        write_data_count = 0;
        count_operate_depth_by_bitwidth_and_depth (data_c_bitwidth, data_DEPTH, data_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_AXILiteS_start_in === 1) begin
            data_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_data_run_flag <= 1; 
            write_data_count = 0;
        end
        if (write_one_data_data_done === 1) begin
            write_data_count = write_data_count + 1;
            if (write_data_count == data_OPERATE_DEPTH) begin
                write_data_run_flag <= 0; 
                data_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_data
    integer write_data_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] data_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = data_c_bitwidth;
    process_num = 10;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_10_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_data_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write data data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (data_c_bitwidth < 32) begin
                        data_data_tmp_reg = mem_data[write_data_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < data_c_bitwidth) begin
                                data_data_tmp_reg[j] = mem_data[write_data_count][i*32 + j];
                            end
                            else begin
                                data_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (data_data_in_addr + write_data_count * four_byte_num * 4 + i * 4, data_data_tmp_reg, write_data_resp);
                end
                process_busy = 0;
                write_one_data_data_done <= 1;
                @(posedge clk);
                write_one_data_data_done <= 0;
            end   
            process_10_finish <= 1;
        end
        @(posedge clk);
    end    
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        write_start_run_flag <= 0; 
        write_start_count <= 0;
    end
    else begin
        if (write_start_count >= 10001) begin
            write_start_run_flag <= 0; 
        end
        else if (TRAN_AXILiteS_write_start_in === 1) begin
            write_start_run_flag <= 1; 
        end
        if (AESL_write_start_finish === 1) begin
            write_start_count <= write_start_count + 1;
            write_start_run_flag <= 0; 
        end
    end
end

initial begin : write_start
    reg [DATA_WIDTH - 1 : 0] write_start_tmp;
    integer process_num;
    integer write_start_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 11;
    while (1) begin
        process_11_finish = 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (write_start_run_flag === 1) begin
                process_busy = 1;
                write_start_tmp=0;
                write_start_tmp[0 : 0] = 1;
                write (START_ADDR, write_start_tmp, write_start_resp);
                process_busy = 0;
                AESL_write_start_finish <= 1;
                @(posedge clk);
                AESL_write_start_finish <= 0;
            end
            process_11_finish <= 1;
        end 
        @(posedge clk);
    end
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        ap_return_read_data_finish <= 0;
        read_ap_return_run_flag <= 0; 
        read_ap_return_count = 0;
        count_operate_depth_by_bitwidth_and_depth (ap_return_c_bitwidth, ap_return_DEPTH, ap_return_OPERATE_DEPTH);
    end
    else begin
        if (AESL_done_index_reg === 1) begin
            read_ap_return_run_flag = 1; 
        end
        if (TRAN_AXILiteS_transaction_done_in === 1) begin
            ap_return_read_data_finish <= 0;
            read_ap_return_count = 0; 
        end
        if (read_one_ap_return_data_done === 1) begin
            read_ap_return_count = read_ap_return_count + 1;
            if (read_ap_return_count == ap_return_OPERATE_DEPTH) begin
                read_ap_return_run_flag <= 0; 
                ap_return_read_data_finish <= 1;
            end
        end
    end
end

initial begin : read_ap_return
    integer read_ap_return_resp;
    integer process_num;
    integer get_vld;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;

    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = ap_return_c_bitwidth;
    process_num = 12;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_12_finish <= 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (read_ap_return_run_flag === 1) begin
                process_busy = 1;
                get_vld = 1;
                if (get_vld == 1) begin
                    //read ap_return data 
                    for (i = 0 ; i < four_byte_num ; i = i+1) begin
                        read (ap_return_data_out_addr + read_ap_return_count * four_byte_num * 4 + i * 4, RDATA_reg, read_ap_return_resp);
                        if (ap_return_c_bitwidth < 32) begin
                            mem_ap_return[read_ap_return_count] <= RDATA_reg;
                        end
                        else begin
                            for (j=0 ; j < 32 ; j = j + 1) begin
                                if (i*32 + j < ap_return_c_bitwidth) begin
                                    mem_ap_return[read_ap_return_count][i*32 + j] <= RDATA_reg[j];
                                end
                            end
                        end
                    end
                    
                    read_one_ap_return_data_done <= 1;
                    @(posedge clk);
                    read_one_ap_return_data_done <= 0;
                end    
                process_busy = 0;
            end    
            process_12_finish <= 1;
        end
        @(posedge clk);
    end    
end
//------------------------Task and function-------------- 
task read_token; 
    input integer fp; 
    output reg [127 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end 
endtask 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_reset_A_V_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [reset_A_V_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (reset_A_V_c_bitwidth , factor);
  fp = $fopen(`TV_IN_reset_A_V ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_reset_A_V); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < reset_A_V_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_reset_A_V [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_reset_A_V [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_reset_A_V [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_reset_A_V [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_reset_A_V [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_reset_V_V_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [reset_V_V_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (reset_V_V_c_bitwidth , factor);
  fp = $fopen(`TV_IN_reset_V_V ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_reset_V_V); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < reset_V_V_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_reset_V_V [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_reset_V_V [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_reset_V_V [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_reset_V_V [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_reset_V_V [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_reset_params_V_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [reset_params_V_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (reset_params_V_c_bitwidth , factor);
  fp = $fopen(`TV_IN_reset_params_V ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_reset_params_V); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < reset_params_V_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_reset_params_V [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_reset_params_V [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_reset_params_V [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_reset_params_V [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_reset_params_V [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_athresh_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [athresh_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (athresh_c_bitwidth , factor);
  fp = $fopen(`TV_IN_athresh ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_athresh); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < athresh_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_athresh [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_athresh [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_athresh [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_athresh [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_athresh [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_vthresh_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [vthresh_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (vthresh_c_bitwidth , factor);
  fp = $fopen(`TV_IN_vthresh ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_vthresh); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < vthresh_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_vthresh [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_vthresh [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_vthresh [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_vthresh [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_vthresh [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_a_flip_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [a_flip_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (a_flip_c_bitwidth , factor);
  fp = $fopen(`TV_IN_a_flip ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_a_flip); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < a_flip_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_a_flip [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_a_flip [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_a_flip [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_a_flip [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_a_flip [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_v_flip_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [v_flip_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (v_flip_c_bitwidth , factor);
  fp = $fopen(`TV_IN_v_flip ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_v_flip); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < v_flip_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_v_flip [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_v_flip [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_v_flip [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_v_flip [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_v_flip [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_a_length_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [a_length_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (a_length_c_bitwidth , factor);
  fp = $fopen(`TV_IN_a_length ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_a_length); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < a_length_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_a_length [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_a_length [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_a_length [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_a_length [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_a_length [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_v_length_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [v_length_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (v_length_c_bitwidth , factor);
  fp = $fopen(`TV_IN_v_length ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_v_length); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < v_length_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_v_length [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_v_length [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_v_length [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_v_length [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_v_length [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_data_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [data_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (data_c_bitwidth , factor);
  fp = $fopen(`TV_IN_data ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_data); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < data_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_data [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_data [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_data [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_data [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_data [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Write file----------------------- 
 
// Write data to file 
 
initial begin : write_ap_return_file_proc 
  integer fp; 
  integer factor; 
  integer transaction_idx; 
  reg [ap_return_c_bitwidth - 1 : 0] mem_tmp; 
  reg [ 100*8 : 1] str;
  integer i; 
  transaction_idx = 0; 
  count_seperate_factor_by_bitwidth (ap_return_c_bitwidth , factor);
  while(1) begin 
      @(posedge clk);
      while (TRAN_AXILiteS_transaction_done_in !== 1) begin
          @(posedge clk);
      end
      # 0.1;
      fp = $fopen(`TV_OUT_ap_return, "a"); 
      if(fp == 0) begin       // Failed to open file 
          $display("Failed to open file \"%s\"!", `TV_OUT_ap_return); 
          $finish; 
      end 
      $fdisplay(fp, "[[transaction]] %d", transaction_idx);
      for (i = 0; i < (ap_return_DEPTH - ap_return_DEPTH % factor); i = i + 1) begin
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_ap_return[i/factor][7:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_ap_return[i/factor][15:8];
              end
              if (i%factor == 2) begin
                  mem_tmp = mem_ap_return[i/factor][23:16];
              end
              if (i%factor == 3) begin
                  mem_tmp = mem_ap_return[i/factor][31:24];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp = mem_ap_return[i/factor][15:0];
              end
              if (i%factor == 1) begin
                  mem_tmp = mem_ap_return[i/factor][31:16];
              end
              $fdisplay(fp,"0x%x",mem_tmp);
          end
          if (factor == 1) begin
              $fdisplay(fp,"0x%x",mem_ap_return[i]);
          end
      end 
      if (factor == 4) begin
          if ((ap_return_DEPTH - 1) % factor == 2) begin
              $fdisplay(fp,"0x%x",mem_ap_return[ap_return_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_ap_return[ap_return_DEPTH / factor][15:8]);
              $fdisplay(fp,"0x%x",mem_ap_return[ap_return_DEPTH / factor][23:16]);
          end
          if ((ap_return_DEPTH - 1) % factor == 1) begin
              $fdisplay(fp,"0x%x",mem_ap_return[ap_return_DEPTH / factor][7:0]);
              $fdisplay(fp,"0x%x",mem_ap_return[ap_return_DEPTH / factor][15:8]);
          end
          if ((ap_return_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_ap_return[ap_return_DEPTH / factor][7:0]);
          end
      end
      if (factor == 2) begin
          if ((ap_return_DEPTH - 1) % factor == 0) begin
              $fdisplay(fp,"0x%x",mem_ap_return[ap_return_DEPTH / factor][15:0]);
          end
      end
      $fdisplay(fp, "[[/transaction]]");
      transaction_idx = transaction_idx + 1;
      $fclose(fp); 
  end 
end 
 
endmodule
