-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ratDecision is
generic (
    C_S_AXI_AXILITES_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_AXILITES_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_AXILiteS_AWVALID : IN STD_LOGIC;
    s_axi_AXILiteS_AWREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_WVALID : IN STD_LOGIC;
    s_axi_AXILiteS_WREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH/8-1 downto 0);
    s_axi_AXILiteS_ARVALID : IN STD_LOGIC;
    s_axi_AXILiteS_ARREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_RVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_RREADY : IN STD_LOGIC;
    s_axi_AXILiteS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_AXILiteS_BVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_BREADY : IN STD_LOGIC;
    s_axi_AXILiteS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of ratDecision is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ratDecision,hls_ip_2016_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.640000,HLS_SYN_LAT=11,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1767,HLS_SYN_LUT=2994}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_st6_fsm_5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_st7_fsm_6 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_st8_fsm_7 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_st9_fsm_8 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_st10_fsm_9 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_st11_fsm_10 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_st12_fsm_11 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_st13_fsm_12 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_st14_fsm_13 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_FFFFFFFE : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111110";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_F0 : STD_LOGIC_VECTOR (12 downto 0) := "0000011110000";
    constant ap_const_lv32_FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111010";
    constant ap_const_lv13_F00 : STD_LOGIC_VECTOR (12 downto 0) := "0111100000000";
    constant ap_const_lv13_F : STD_LOGIC_VECTOR (12 downto 0) := "0000000001111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_31 : BOOLEAN;
    signal ap_ready : STD_LOGIC;
    signal reset_A_V : STD_LOGIC_VECTOR (0 downto 0);
    signal reset_V_V : STD_LOGIC_VECTOR (0 downto 0);
    signal reset_params_V : STD_LOGIC_VECTOR (0 downto 0);
    signal athresh : STD_LOGIC_VECTOR (31 downto 0);
    signal vthresh : STD_LOGIC_VECTOR (31 downto 0);
    signal a_flip : STD_LOGIC_VECTOR (7 downto 0);
    signal v_flip : STD_LOGIC_VECTOR (7 downto 0);
    signal a_length : STD_LOGIC_VECTOR (31 downto 0);
    signal v_length : STD_LOGIC_VECTOR (31 downto 0);
    signal data : STD_LOGIC_VECTOR (15 downto 0);
    signal AstimDelay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal VstimDelay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ACaptureThresh : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    signal VCaptureThresh : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    signal v_thresh : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal a_thresh : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal aflip : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal vflip : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal recentdatapoints_len : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentdatapoints_head_i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentdatapoints_sum : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentdatapoints_data_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal recentdatapoints_data_ce0 : STD_LOGIC;
    signal recentdatapoints_data_we0 : STD_LOGIC;
    signal recentdatapoints_data_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal AbeatDelay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal VbeatDelay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal VbeatFallDelay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentVBools_sum : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentVBools_head_i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentVBools_len : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentVBools_data_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal recentVBools_data_ce0 : STD_LOGIC;
    signal recentVBools_data_we0 : STD_LOGIC;
    signal recentVBools_data_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal recentVBools_data_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal recentVBools_data_ce1 : STD_LOGIC;
    signal recentVBools_data_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_sample_is_V_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal recentABools_sum : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentABools_head_i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentABools_len : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentABools_data_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal recentABools_data_ce0 : STD_LOGIC;
    signal recentABools_data_we0 : STD_LOGIC;
    signal recentABools_data_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal recentABools_data_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal recentABools_data_ce1 : STD_LOGIC;
    signal recentABools_data_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_sample_is_A_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal data_read_reg_1493 : STD_LOGIC_VECTOR (15 downto 0);
    signal val_assign_fu_424_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_assign_reg_1511 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentdatapoints_data_addr_reg_1531 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_495_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_reg_1536 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_509_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_reg_1542 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_38_i_fu_560_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_38_i_reg_1548 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_176 : BOOLEAN;
    signal p_tmp_i_fu_585_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_tmp_i_reg_1554 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_187 : BOOLEAN;
    signal recentVBools_data_addr_reg_1571 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1576 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_200 : BOOLEAN;
    signal recentVBools_data_load_reg_1582 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_704_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_reg_1587 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st5_fsm_4 : STD_LOGIC;
    signal ap_sig_210 : BOOLEAN;
    signal tmp_4_fu_714_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_reg_1594 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_724_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_reg_1601 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_read_assign_fu_764_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_read_assign_reg_1608 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_read_assign_1_fu_776_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_read_assign_1_reg_1614 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_head_i_read_ass_fu_795_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_head_i_read_ass_reg_1622 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_809_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_1628 : STD_LOGIC_VECTOR (0 downto 0);
    signal CircularBuffer_len_write_assig_fu_815_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_write_assig_reg_1632 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st6_fsm_5 : STD_LOGIC;
    signal ap_sig_236 : BOOLEAN;
    signal not_tmp_i_i4_fu_883_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_i_i4_reg_1648 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_5_fu_893_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_5_reg_1653 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st7_fsm_6 : STD_LOGIC;
    signal ap_sig_249 : BOOLEAN;
    signal toReturn_6_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_6_reg_1658 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_sample_is_V_V_load_load_fu_960_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st8_fsm_7 : STD_LOGIC;
    signal ap_sig_260 : BOOLEAN;
    signal tmp_i3_fu_976_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i3_reg_1672 : STD_LOGIC_VECTOR (0 downto 0);
    signal recentABools_data_addr_reg_1687 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_12_fu_1037_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1692 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st9_fsm_8 : STD_LOGIC;
    signal ap_sig_277 : BOOLEAN;
    signal recentABools_data_load_reg_1698 : STD_LOGIC_VECTOR (0 downto 0);
    signal CircularBuffer_sum_read_assign_1_fu_1077_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_read_assign_1_reg_1703 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st10_fsm_9 : STD_LOGIC;
    signal ap_sig_287 : BOOLEAN;
    signal CircularBuffer_len_read_assign_3_fu_1089_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_read_assign_3_reg_1709 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_head_i_read_ass_1_fu_1108_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_head_i_read_ass_1_reg_1717 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_1122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_1723 : STD_LOGIC_VECTOR (0 downto 0);
    signal CircularBuffer_len_write_assig_2_fu_1140_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_write_assig_2_reg_1727 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st11_fsm_10 : STD_LOGIC;
    signal ap_sig_307 : BOOLEAN;
    signal not_tmp_i_i2_fu_1208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_i_i2_reg_1743 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_7_fu_1218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_7_reg_1748 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st12_fsm_11 : STD_LOGIC;
    signal ap_sig_320 : BOOLEAN;
    signal toReturn_8_fu_1224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_8_reg_1753 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_sample_is_A_V_load_load_fu_1285_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st13_fsm_12 : STD_LOGIC;
    signal ap_sig_331 : BOOLEAN;
    signal tmp_22_fu_1319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_1770 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_1324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_reg_1775 : STD_LOGIC_VECTOR (0 downto 0);
    signal ACaptureThresh_loc_reg_286 : STD_LOGIC_VECTOR (31 downto 0);
    signal reset_params_V_read_read_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal VCaptureThresh_loc_reg_296 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_write_assig_1_fu_915_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_phi_fu_309_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_reg_306 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_write_assig_1_fu_922_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentVBools_len_new_phi_fu_318_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentVBools_len_new_reg_315 : STD_LOGIC_VECTOR (31 downto 0);
    signal VbeatDelay_new_1_reg_324 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal VbeatFallDelay_new_1_reg_340 : STD_LOGIC_VECTOR (31 downto 0);
    signal last_sample_is_V_V_loc_2_reg_356 : STD_LOGIC_VECTOR (0 downto 0);
    signal CircularBuffer_sum_write_assig_3_fu_1240_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_phi_fu_377_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_reg_374 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_write_assig_3_fu_1247_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentABools_len_new_phi_fu_386_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentABools_len_new_reg_383 : STD_LOGIC_VECTOR (31 downto 0);
    signal AbeatDelay_new_reg_392 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_1267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_1301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_407 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_4_fu_484_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_41_i_fu_631_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_i2_5_fu_640_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_28_i_i_fu_847_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_28_i_i9_fu_878_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_i3_6_fu_981_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_i4_7_fu_989_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_28_i_i1_fu_1172_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_28_i_i2_fu_1203_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal AstimDelay_new_fu_1418_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st14_fsm_13 : STD_LOGIC;
    signal ap_sig_434 : BOOLEAN;
    signal VstimDelay_new_fu_1468_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_37_i_fu_549_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal AstimDelay_load_op_fu_489_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal VstimDelay_load_op_fu_503_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal extLd_fu_531_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_i_fu_535_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentdatapoints_sum_loc_i_fu_541_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentdatapoints_len_load_op_fu_554_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_39_i_fu_574_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_40_i_fu_579_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_605_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_610_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_fu_618_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_i_fu_623_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i1_fu_645_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal datapointV_fu_650_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal datapointV_cast_fu_658_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_9_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal datapointV_1_fu_672_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_s_fu_678_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_cast_fu_686_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal extLd1_fu_747_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i2_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_i_fu_750_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_int_60_sum_i_fu_756_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_assign_1_fu_730_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_read_assign_fu_770_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_33_i_fu_784_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_34_i_fu_789_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_2_fu_821_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_26_fu_825_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_3_fu_833_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_4_fu_839_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_5_fu_852_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_27_fu_856_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_6_fu_864_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_7_fu_870_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal not_tmp_i_i_fu_888_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_i_cast_fu_904_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_write_assig_fu_907_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal toReturn_i12_cast_fu_912_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_928_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_2_fu_938_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal datapointA_fu_994_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal datapointA_cast_fu_1001_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_11_fu_1009_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal datapointA_1_fu_1015_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_1_fu_1021_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_1_cast_fu_1029_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal extLd2_fu_1060_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i4_fu_1054_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_i1_fu_1063_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_int_60_sum_i1_fu_1069_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_assign_2_fu_1043_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_read_assign_2_fu_1083_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_33_i1_fu_1097_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_34_i1_fu_1102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_8_fu_1146_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_28_fu_1150_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_9_fu_1158_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_10_fu_1164_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_11_fu_1177_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_fu_1181_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_12_fu_1189_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_13_fu_1195_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal not_tmp_i_i1_fu_1213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_i25_cast_fu_1229_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_write_assig_2_fu_1232_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal toReturn_i38_cast_fu_1237_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_1253_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_15_fu_1263_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_1289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_1295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_not_fu_1335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_sample_is_V_V_loc_2_not_fu_1341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_fu_1347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_1353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_1367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_2_fu_1359_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_21_not_not_fu_1381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_1387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_1373_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_21_fu_1401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_1_fu_1393_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_cond1_fu_1407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_fu_1412_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_24_fu_1439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_1451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_1433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_2_fu_1425_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_cond3_fu_1456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_4_fu_1462_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal toReturn_3_fu_1475_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_sig_151 : BOOLEAN;
    signal ap_sig_409 : BOOLEAN;
    signal ap_sig_405 : BOOLEAN;
    signal ap_sig_368 : BOOLEAN;
    signal ap_sig_366 : BOOLEAN;

    component ratDecision_recentdatapoints_data IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component ratDecision_recentVBools_data IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component ratDecision_AXILiteS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (15 downto 0);
        reset_A_V : OUT STD_LOGIC_VECTOR (0 downto 0);
        reset_V_V : OUT STD_LOGIC_VECTOR (0 downto 0);
        reset_params_V : OUT STD_LOGIC_VECTOR (0 downto 0);
        athresh : OUT STD_LOGIC_VECTOR (31 downto 0);
        vthresh : OUT STD_LOGIC_VECTOR (31 downto 0);
        a_flip : OUT STD_LOGIC_VECTOR (7 downto 0);
        v_flip : OUT STD_LOGIC_VECTOR (7 downto 0);
        a_length : OUT STD_LOGIC_VECTOR (31 downto 0);
        v_length : OUT STD_LOGIC_VECTOR (31 downto 0);
        data : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    recentdatapoints_data_U : component ratDecision_recentdatapoints_data
    generic map (
        DataWidth => 16,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => recentdatapoints_data_address0,
        ce0 => recentdatapoints_data_ce0,
        we0 => recentdatapoints_data_we0,
        d0 => data_read_reg_1493,
        q0 => recentdatapoints_data_q0);

    recentVBools_data_U : component ratDecision_recentVBools_data
    generic map (
        DataWidth => 1,
        AddressRange => 60,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => recentVBools_data_address0,
        ce0 => recentVBools_data_ce0,
        we0 => recentVBools_data_we0,
        d0 => tmp_s_reg_1576,
        q0 => recentVBools_data_q0,
        address1 => recentVBools_data_address1,
        ce1 => recentVBools_data_ce1,
        q1 => recentVBools_data_q1);

    recentABools_data_U : component ratDecision_recentVBools_data
    generic map (
        DataWidth => 1,
        AddressRange => 60,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => recentABools_data_address0,
        ce0 => recentABools_data_ce0,
        we0 => recentABools_data_we0,
        d0 => tmp_12_reg_1692,
        q0 => recentABools_data_q0,
        address1 => recentABools_data_address1,
        ce1 => recentABools_data_ce1,
        q1 => recentABools_data_q1);

    ratDecision_AXILiteS_s_axi_U : component ratDecision_AXILiteS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_AXILITES_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_AXILITES_DATA_WIDTH)
    port map (
        AWVALID => s_axi_AXILiteS_AWVALID,
        AWREADY => s_axi_AXILiteS_AWREADY,
        AWADDR => s_axi_AXILiteS_AWADDR,
        WVALID => s_axi_AXILiteS_WVALID,
        WREADY => s_axi_AXILiteS_WREADY,
        WDATA => s_axi_AXILiteS_WDATA,
        WSTRB => s_axi_AXILiteS_WSTRB,
        ARVALID => s_axi_AXILiteS_ARVALID,
        ARREADY => s_axi_AXILiteS_ARREADY,
        ARADDR => s_axi_AXILiteS_ARADDR,
        RVALID => s_axi_AXILiteS_RVALID,
        RREADY => s_axi_AXILiteS_RREADY,
        RDATA => s_axi_AXILiteS_RDATA,
        RRESP => s_axi_AXILiteS_RRESP,
        BVALID => s_axi_AXILiteS_BVALID,
        BREADY => s_axi_AXILiteS_BREADY,
        BRESP => s_axi_AXILiteS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        ap_return => ap_return,
        reset_A_V => reset_A_V,
        reset_V_V => reset_V_V,
        reset_params_V => reset_params_V,
        athresh => athresh,
        vthresh => vthresh,
        a_flip => a_flip,
        v_flip => v_flip,
        a_length => a_length,
        v_length => v_length,
        data => data);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ACaptureThresh_loc_reg_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_151) then
                if ((ap_const_lv1_0 = reset_params_V_read_read_fu_178_p2)) then 
                    ACaptureThresh_loc_reg_286 <= ACaptureThresh;
                elsif (not((ap_const_lv1_0 = reset_params_V_read_read_fu_178_p2))) then 
                    ACaptureThresh_loc_reg_286 <= a_length;
                end if;
            end if; 
        end if;
    end process;

    AbeatDelay_new_reg_392_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and (ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1) and not((ap_const_lv1_0 = tmp_16_fu_1267_p2)) and not((ap_const_lv1_0 = or_cond_fu_1301_p2)))) then 
                AbeatDelay_new_reg_392 <= ap_const_lv32_0;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1)) and not((ap_const_lv1_0 = tmp_16_fu_1267_p2)) and not((ap_const_lv1_0 = or_cond_fu_1301_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and ((not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1)) and (ap_const_lv1_0 = tmp_16_fu_1267_p2)) or (not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1)) and (ap_const_lv1_0 = or_cond_fu_1301_p2)))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and (((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1) and (ap_const_lv1_0 = tmp_16_fu_1267_p2)) or ((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1) and (ap_const_lv1_0 = or_cond_fu_1301_p2)))))) then 
                AbeatDelay_new_reg_392 <= tmp_3_reg_1587;
            end if; 
        end if;
    end process;

    VCaptureThresh_loc_reg_296_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_151) then
                if ((ap_const_lv1_0 = reset_params_V_read_read_fu_178_p2)) then 
                    VCaptureThresh_loc_reg_296 <= VCaptureThresh;
                elsif (not((ap_const_lv1_0 = reset_params_V_read_read_fu_178_p2))) then 
                    VCaptureThresh_loc_reg_296 <= v_length;
                end if;
            end if; 
        end if;
    end process;

    VbeatDelay_new_1_reg_324_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1) and not((ap_const_lv1_0 = tmp_10_fu_942_p2)))) then 
                VbeatDelay_new_1_reg_324 <= ap_const_lv32_0;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1)) and not((ap_const_lv1_0 = tmp_10_fu_942_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1)) and (ap_const_lv1_0 = tmp_10_fu_942_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1) and (ap_const_lv1_0 = tmp_10_fu_942_p2)))) then 
                VbeatDelay_new_1_reg_324 <= tmp_4_reg_1594;
            end if; 
        end if;
    end process;

    VbeatFallDelay_new_1_reg_340_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1)) and (ap_const_lv1_0 = tmp_10_fu_942_p2))) then 
                VbeatFallDelay_new_1_reg_340 <= ap_const_lv32_0;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1)) and not((ap_const_lv1_0 = tmp_10_fu_942_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1) and not((ap_const_lv1_0 = tmp_10_fu_942_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1) and (ap_const_lv1_0 = tmp_10_fu_942_p2)))) then 
                VbeatFallDelay_new_1_reg_340 <= tmp_5_reg_1601;
            end if; 
        end if;
    end process;

    last_sample_is_A_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12)) then
                if (ap_sig_405) then 
                    last_sample_is_A_V <= ap_const_lv1_1;
                elsif (ap_sig_409) then 
                    last_sample_is_A_V <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;

    last_sample_is_V_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7)) then
                if (ap_sig_366) then 
                    last_sample_is_V_V <= ap_const_lv1_1;
                elsif (ap_sig_368) then 
                    last_sample_is_V_V <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;

    last_sample_is_V_V_loc_2_reg_356_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1)) and (ap_const_lv1_0 = tmp_10_fu_942_p2))) then 
                last_sample_is_V_V_loc_2_reg_356 <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1) and not((ap_const_lv1_0 = tmp_10_fu_942_p2)))) then 
                last_sample_is_V_V_loc_2_reg_356 <= ap_const_lv1_1;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1)) and not((ap_const_lv1_0 = tmp_10_fu_942_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1) and (ap_const_lv1_0 = tmp_10_fu_942_p2)))) then 
                last_sample_is_V_V_loc_2_reg_356 <= last_sample_is_V_V;
            end if; 
        end if;
    end process;

    recentABools_len_new_reg_383_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9) and (ap_const_lv1_0 = tmp_13_fu_1122_p2))) then 
                recentABools_len_new_reg_383 <= CircularBuffer_len_read_assign_3_fu_1089_p3;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = tmp_13_reg_1723)))) then 
                recentABools_len_new_reg_383 <= CircularBuffer_len_write_assig_3_fu_1247_p2;
            end if; 
        end if;
    end process;

    recentVBools_len_new_reg_315_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and (ap_const_lv1_0 = tmp_8_fu_809_p2))) then 
                recentVBools_len_new_reg_315 <= CircularBuffer_len_read_assign_1_fu_776_p3;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = tmp_8_reg_1628)))) then 
                recentVBools_len_new_reg_315 <= CircularBuffer_len_write_assig_1_fu_922_p2;
            end if; 
        end if;
    end process;

    sum_1_reg_374_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9) and (ap_const_lv1_0 = tmp_13_fu_1122_p2))) then 
                sum_1_reg_374 <= CircularBuffer_sum_read_assign_1_fu_1077_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = tmp_13_reg_1723)))) then 
                sum_1_reg_374 <= CircularBuffer_sum_write_assig_3_fu_1240_p2;
            end if; 
        end if;
    end process;

    sum_reg_306_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and (ap_const_lv1_0 = tmp_8_fu_809_p2))) then 
                sum_reg_306 <= CircularBuffer_sum_read_assign_fu_764_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = tmp_8_reg_1628)))) then 
                sum_reg_306 <= CircularBuffer_sum_write_assig_1_fu_915_p2;
            end if; 
        end if;
    end process;

    tmp_19_reg_407_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and ((not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1)) and (ap_const_lv1_0 = tmp_16_fu_1267_p2)) or (not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1)) and (ap_const_lv1_0 = or_cond_fu_1301_p2))))) then 
                tmp_19_reg_407 <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and (ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1) and not((ap_const_lv1_0 = tmp_16_fu_1267_p2)) and not((ap_const_lv1_0 = or_cond_fu_1301_p2)))) then 
                tmp_19_reg_407 <= ap_const_lv1_1;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1)) and not((ap_const_lv1_0 = tmp_16_fu_1267_p2)) and not((ap_const_lv1_0 = or_cond_fu_1301_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and (((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1) and (ap_const_lv1_0 = tmp_16_fu_1267_p2)) or ((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1) and (ap_const_lv1_0 = or_cond_fu_1301_p2)))))) then 
                tmp_19_reg_407 <= last_sample_is_A_V;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)) and not((ap_const_lv1_0 = reset_params_V_read_read_fu_178_p2)))) then
                ACaptureThresh <= a_length;
                VCaptureThresh <= v_length;
                a_thresh <= athresh;
                aflip <= a_flip;
                v_thresh <= vthresh;
                vflip <= v_flip;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st14_fsm_13)) then
                AbeatDelay <= AbeatDelay_new_reg_392;
                AstimDelay <= AstimDelay_new_fu_1418_p3;
                VstimDelay <= VstimDelay_new_fu_1468_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9)) then
                CircularBuffer_head_i_read_ass_1_reg_1717 <= CircularBuffer_head_i_read_ass_1_fu_1108_p3;
                CircularBuffer_len_read_assign_3_reg_1709 <= CircularBuffer_len_read_assign_3_fu_1089_p3;
                CircularBuffer_sum_read_assign_1_reg_1703 <= CircularBuffer_sum_read_assign_1_fu_1077_p2;
                VbeatDelay <= VbeatDelay_new_1_reg_324;
                VbeatFallDelay <= VbeatFallDelay_new_1_reg_340;
                recentABools_head_i <= CircularBuffer_head_i_read_ass_1_fu_1108_p3;
                tmp_13_reg_1723 <= tmp_13_fu_1122_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then
                CircularBuffer_head_i_read_ass_reg_1622 <= CircularBuffer_head_i_read_ass_fu_795_p3;
                CircularBuffer_len_read_assign_1_reg_1614 <= CircularBuffer_len_read_assign_1_fu_776_p3;
                CircularBuffer_sum_read_assign_reg_1608 <= CircularBuffer_sum_read_assign_fu_764_p2;
                recentVBools_head_i <= CircularBuffer_head_i_read_ass_fu_795_p3;
                tmp_3_reg_1587 <= tmp_3_fu_704_p2;
                tmp_4_reg_1594 <= tmp_4_fu_714_p2;
                tmp_5_reg_1601 <= tmp_5_fu_724_p2;
                tmp_8_reg_1628 <= tmp_8_fu_809_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9) and not((ap_const_lv1_0 = tmp_13_fu_1122_p2)))) then
                CircularBuffer_len_write_assig_2_reg_1727 <= CircularBuffer_len_write_assig_2_fu_1140_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = tmp_8_fu_809_p2)))) then
                CircularBuffer_len_write_assig_reg_1632 <= CircularBuffer_len_write_assig_fu_815_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)))) then
                data_read_reg_1493 <= data;
                recentdatapoints_data_addr_reg_1531 <= tmp_i_4_fu_484_p1(3 - 1 downto 0);
                tmp_6_reg_1536 <= tmp_6_fu_495_p3;
                tmp_7_reg_1542 <= tmp_7_fu_509_p3;
                val_assign_reg_1511 <= val_assign_fu_424_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10)) then
                not_tmp_i_i2_reg_1743 <= not_tmp_i_i2_fu_1208_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5)) then
                not_tmp_i_i4_reg_1648 <= not_tmp_i_i4_fu_883_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then
                p_tmp_i_reg_1554 <= p_tmp_i_fu_585_p3;
                recentdatapoints_head_i <= p_tmp_i_fu_585_p3;
                recentdatapoints_len <= tmp_38_i_fu_560_p3;
                recentdatapoints_sum <= tmp_37_i_fu_549_p2;
                tmp_38_i_reg_1548 <= tmp_38_i_fu_560_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7)) then
                recentABools_data_addr_reg_1687 <= tmp_i4_7_fu_989_p1(6 - 1 downto 0);
                recentVBools_len <= recentVBools_len_new_phi_fu_318_p4;
                recentVBools_sum <= sum_phi_fu_309_p4;
                tmp_i3_reg_1672 <= tmp_i3_fu_976_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8)) then
                recentABools_data_load_reg_1698 <= recentABools_data_q0;
                tmp_12_reg_1692 <= tmp_12_fu_1037_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12)) then
                recentABools_len <= recentABools_len_new_phi_fu_386_p4;
                recentABools_sum <= sum_1_phi_fu_377_p4;
                tmp_22_reg_1770 <= tmp_22_fu_1319_p2;
                tmp_25_reg_1775 <= tmp_25_fu_1324_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then
                recentVBools_data_addr_reg_1571 <= tmp_i2_5_fu_640_p1(6 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then
                recentVBools_data_load_reg_1582 <= recentVBools_data_q0;
                tmp_s_reg_1576 <= tmp_s_fu_694_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6)) then
                toReturn_5_reg_1653 <= toReturn_5_fu_893_p2;
                toReturn_6_reg_1658 <= toReturn_6_fu_899_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st12_fsm_11)) then
                toReturn_7_reg_1748 <= toReturn_7_fu_1218_p2;
                toReturn_8_reg_1753 <= toReturn_8_fu_1224_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, tmp_8_fu_809_p2, tmp_13_fu_1122_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                ap_NS_fsm <= ap_ST_st3_fsm_2;
            when ap_ST_st3_fsm_2 => 
                ap_NS_fsm <= ap_ST_st4_fsm_3;
            when ap_ST_st4_fsm_3 => 
                ap_NS_fsm <= ap_ST_st5_fsm_4;
            when ap_ST_st5_fsm_4 => 
                if ((ap_const_lv1_0 = tmp_8_fu_809_p2)) then
                    ap_NS_fsm <= ap_ST_st8_fsm_7;
                else
                    ap_NS_fsm <= ap_ST_st6_fsm_5;
                end if;
            when ap_ST_st6_fsm_5 => 
                ap_NS_fsm <= ap_ST_st7_fsm_6;
            when ap_ST_st7_fsm_6 => 
                ap_NS_fsm <= ap_ST_st8_fsm_7;
            when ap_ST_st8_fsm_7 => 
                ap_NS_fsm <= ap_ST_st9_fsm_8;
            when ap_ST_st9_fsm_8 => 
                ap_NS_fsm <= ap_ST_st10_fsm_9;
            when ap_ST_st10_fsm_9 => 
                if ((ap_const_lv1_0 = tmp_13_fu_1122_p2)) then
                    ap_NS_fsm <= ap_ST_st13_fsm_12;
                else
                    ap_NS_fsm <= ap_ST_st11_fsm_10;
                end if;
            when ap_ST_st11_fsm_10 => 
                ap_NS_fsm <= ap_ST_st12_fsm_11;
            when ap_ST_st12_fsm_11 => 
                ap_NS_fsm <= ap_ST_st13_fsm_12;
            when ap_ST_st13_fsm_12 => 
                ap_NS_fsm <= ap_ST_st14_fsm_13;
            when ap_ST_st14_fsm_13 => 
                ap_NS_fsm <= ap_ST_st1_fsm_0;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    AstimDelay_load_op_fu_489_p2 <= std_logic_vector(unsigned(AstimDelay) + unsigned(ap_const_lv32_1));
    AstimDelay_new_fu_1418_p3 <= 
        ap_const_lv32_0 when (or_cond1_fu_1407_p2(0) = '1') else 
        tmp_6_reg_1536;
    CircularBuffer_head_i_read_ass_1_fu_1108_p3 <= 
        ap_const_lv32_0 when (tmp_34_i1_fu_1102_p2(0) = '1') else 
        tmp_33_i1_fu_1097_p2;
    CircularBuffer_head_i_read_ass_fu_795_p3 <= 
        ap_const_lv32_0 when (tmp_34_i_fu_789_p2(0) = '1') else 
        tmp_33_i_fu_784_p2;
    CircularBuffer_int_60_sum_i1_fu_1069_p3 <= 
        tmp_29_i1_fu_1063_p2 when (tmp_i4_fu_1054_p2(0) = '1') else 
        recentABools_sum;
    CircularBuffer_int_60_sum_i_fu_756_p3 <= 
        tmp_29_i_fu_750_p2 when (tmp_i2_fu_741_p2(0) = '1') else 
        recentVBools_sum;
    CircularBuffer_len_read_assign_1_fu_776_p3 <= 
        ap_const_lv32_3C when (tmp_i2_fu_741_p2(0) = '1') else 
        CircularBuffer_len_read_assign_fu_770_p2;
    CircularBuffer_len_read_assign_2_fu_1083_p2 <= std_logic_vector(unsigned(recentABools_len) + unsigned(ap_const_lv32_1));
    CircularBuffer_len_read_assign_3_fu_1089_p3 <= 
        ap_const_lv32_3C when (tmp_i4_fu_1054_p2(0) = '1') else 
        CircularBuffer_len_read_assign_2_fu_1083_p2;
    CircularBuffer_len_read_assign_fu_770_p2 <= std_logic_vector(unsigned(recentVBools_len) + unsigned(ap_const_lv32_1));
    CircularBuffer_len_write_assig_1_fu_922_p2 <= std_logic_vector(unsigned(CircularBuffer_len_read_assign_1_reg_1614) + unsigned(ap_const_lv32_FFFFFFFE));
    CircularBuffer_len_write_assig_2_fu_1140_p2 <= std_logic_vector(unsigned(CircularBuffer_len_read_assign_3_fu_1089_p3) + unsigned(ap_const_lv32_FFFFFFFF));
    CircularBuffer_len_write_assig_3_fu_1247_p2 <= std_logic_vector(unsigned(CircularBuffer_len_read_assign_3_reg_1709) + unsigned(ap_const_lv32_FFFFFFFE));
    CircularBuffer_len_write_assig_fu_815_p2 <= std_logic_vector(unsigned(CircularBuffer_len_read_assign_1_fu_776_p3) + unsigned(ap_const_lv32_FFFFFFFF));
    CircularBuffer_sum_read_assign_1_fu_1077_p2 <= std_logic_vector(unsigned(CircularBuffer_int_60_sum_i1_fu_1069_p3) + unsigned(val_assign_2_fu_1043_p1));
    CircularBuffer_sum_read_assign_fu_764_p2 <= std_logic_vector(unsigned(CircularBuffer_int_60_sum_i_fu_756_p3) + unsigned(val_assign_1_fu_730_p1));
    CircularBuffer_sum_write_assig_1_fu_915_p2 <= std_logic_vector(unsigned(CircularBuffer_sum_write_assig_fu_907_p2) - unsigned(toReturn_i12_cast_fu_912_p1));
    CircularBuffer_sum_write_assig_2_fu_1232_p2 <= std_logic_vector(unsigned(CircularBuffer_sum_read_assign_1_reg_1703) - unsigned(toReturn_i25_cast_fu_1229_p1));
    CircularBuffer_sum_write_assig_3_fu_1240_p2 <= std_logic_vector(unsigned(CircularBuffer_sum_write_assig_2_fu_1232_p2) - unsigned(toReturn_i38_cast_fu_1237_p1));
    CircularBuffer_sum_write_assig_fu_907_p2 <= std_logic_vector(unsigned(CircularBuffer_sum_read_assign_reg_1608) - unsigned(toReturn_i_cast_fu_904_p1));
    VstimDelay_load_op_fu_503_p2 <= std_logic_vector(unsigned(VstimDelay) + unsigned(ap_const_lv32_1));
    VstimDelay_new_fu_1468_p3 <= 
        ap_const_lv32_0 when (or_cond3_fu_1456_p2(0) = '1') else 
        tmp_7_reg_1542;

    ap_done_assign_proc : process(ap_sig_cseq_ST_st14_fsm_13)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st14_fsm_13)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_sig_cseq_ST_st14_fsm_13)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st14_fsm_13)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

        ap_return <= std_logic_vector(resize(signed(toReturn_3_fu_1475_p3),16));


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_151_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
                ap_sig_151 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)));
    end process;


    ap_sig_176_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_176 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_187_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_187 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_200_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_200 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_210_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_210 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    ap_sig_236_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_236 <= (ap_const_lv1_1 = ap_CS_fsm(5 downto 5));
    end process;


    ap_sig_249_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_249 <= (ap_const_lv1_1 = ap_CS_fsm(6 downto 6));
    end process;


    ap_sig_260_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_260 <= (ap_const_lv1_1 = ap_CS_fsm(7 downto 7));
    end process;


    ap_sig_277_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_277 <= (ap_const_lv1_1 = ap_CS_fsm(8 downto 8));
    end process;


    ap_sig_287_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_287 <= (ap_const_lv1_1 = ap_CS_fsm(9 downto 9));
    end process;


    ap_sig_307_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_307 <= (ap_const_lv1_1 = ap_CS_fsm(10 downto 10));
    end process;


    ap_sig_31_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_31 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_320_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_320 <= (ap_const_lv1_1 = ap_CS_fsm(11 downto 11));
    end process;


    ap_sig_331_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_331 <= (ap_const_lv1_1 = ap_CS_fsm(12 downto 12));
    end process;


    ap_sig_366_assign_proc : process(last_sample_is_V_V_load_load_fu_960_p1, tmp_10_fu_942_p2)
    begin
                ap_sig_366 <= ((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1) and not((ap_const_lv1_0 = tmp_10_fu_942_p2)));
    end process;


    ap_sig_368_assign_proc : process(last_sample_is_V_V_load_load_fu_960_p1, tmp_10_fu_942_p2)
    begin
                ap_sig_368 <= (not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_960_p1)) and (ap_const_lv1_0 = tmp_10_fu_942_p2));
    end process;


    ap_sig_405_assign_proc : process(last_sample_is_A_V_load_load_fu_1285_p1, tmp_16_fu_1267_p2, or_cond_fu_1301_p2)
    begin
                ap_sig_405 <= ((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1) and not((ap_const_lv1_0 = tmp_16_fu_1267_p2)) and not((ap_const_lv1_0 = or_cond_fu_1301_p2)));
    end process;


    ap_sig_409_assign_proc : process(last_sample_is_A_V_load_load_fu_1285_p1, tmp_16_fu_1267_p2, or_cond_fu_1301_p2)
    begin
                ap_sig_409 <= ((not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1)) and (ap_const_lv1_0 = tmp_16_fu_1267_p2)) or (not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1285_p1)) and (ap_const_lv1_0 = or_cond_fu_1301_p2)));
    end process;


    ap_sig_434_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_434 <= (ap_const_lv1_1 = ap_CS_fsm(13 downto 13));
    end process;


    ap_sig_cseq_ST_st10_fsm_9_assign_proc : process(ap_sig_287)
    begin
        if (ap_sig_287) then 
            ap_sig_cseq_ST_st10_fsm_9 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st10_fsm_9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st11_fsm_10_assign_proc : process(ap_sig_307)
    begin
        if (ap_sig_307) then 
            ap_sig_cseq_ST_st11_fsm_10 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st11_fsm_10 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st12_fsm_11_assign_proc : process(ap_sig_320)
    begin
        if (ap_sig_320) then 
            ap_sig_cseq_ST_st12_fsm_11 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st12_fsm_11 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st13_fsm_12_assign_proc : process(ap_sig_331)
    begin
        if (ap_sig_331) then 
            ap_sig_cseq_ST_st13_fsm_12 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st13_fsm_12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st14_fsm_13_assign_proc : process(ap_sig_434)
    begin
        if (ap_sig_434) then 
            ap_sig_cseq_ST_st14_fsm_13 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st14_fsm_13 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_31)
    begin
        if (ap_sig_31) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_176)
    begin
        if (ap_sig_176) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_187)
    begin
        if (ap_sig_187) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_200)
    begin
        if (ap_sig_200) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st5_fsm_4_assign_proc : process(ap_sig_210)
    begin
        if (ap_sig_210) then 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st6_fsm_5_assign_proc : process(ap_sig_236)
    begin
        if (ap_sig_236) then 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st7_fsm_6_assign_proc : process(ap_sig_249)
    begin
        if (ap_sig_249) then 
            ap_sig_cseq_ST_st7_fsm_6 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st7_fsm_6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st8_fsm_7_assign_proc : process(ap_sig_260)
    begin
        if (ap_sig_260) then 
            ap_sig_cseq_ST_st8_fsm_7 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st8_fsm_7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st9_fsm_8_assign_proc : process(ap_sig_277)
    begin
        if (ap_sig_277) then 
            ap_sig_cseq_ST_st9_fsm_8 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st9_fsm_8 <= ap_const_logic_0;
        end if; 
    end process;

    brmerge_fu_1347_p2 <= (tmp_21_not_fu_1335_p2 or last_sample_is_V_V_loc_2_not_fu_1341_p2);
    datapointA_1_fu_1015_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(datapointA_cast_fu_1001_p1));
        datapointA_cast_fu_1001_p1 <= std_logic_vector(resize(signed(datapointA_fu_994_p3),17));

    datapointA_fu_994_p3 <= 
        recentdatapoints_data_q0 when (tmp_i3_reg_1672(0) = '1') else 
        ap_const_lv16_0;
    datapointV_1_fu_672_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(datapointV_cast_fu_658_p1));
        datapointV_cast_fu_658_p1 <= std_logic_vector(resize(signed(datapointV_fu_650_p3),17));

    datapointV_fu_650_p3 <= 
        ap_const_lv16_0 when (tmp_i1_fu_645_p2(0) = '1') else 
        recentdatapoints_data_q0;
    extLd1_fu_747_p1 <= std_logic_vector(resize(unsigned(recentVBools_data_load_reg_1582),32));
    extLd2_fu_1060_p1 <= std_logic_vector(resize(unsigned(recentABools_data_load_reg_1698),32));
        extLd_fu_531_p1 <= std_logic_vector(resize(signed(recentdatapoints_data_q0),32));

    i_10_fu_1164_p3 <= 
        i_9_fu_1158_p2 when (tmp_28_fu_1150_p3(0) = '1') else 
        i_8_fu_1146_p2;
    i_11_fu_1177_p2 <= std_logic_vector(unsigned(CircularBuffer_head_i_read_ass_1_reg_1717) - unsigned(CircularBuffer_len_write_assig_2_reg_1727));
    i_12_fu_1189_p2 <= std_logic_vector(unsigned(i_11_fu_1177_p2) + unsigned(ap_const_lv32_3C));
    i_13_fu_1195_p3 <= 
        i_12_fu_1189_p2 when (tmp_29_fu_1181_p3(0) = '1') else 
        i_11_fu_1177_p2;
    i_1_fu_618_p2 <= std_logic_vector(unsigned(p_tmp_i_reg_1554) + unsigned(ap_const_lv32_4));
    i_2_fu_821_p2 <= std_logic_vector(unsigned(CircularBuffer_head_i_read_ass_reg_1622) - unsigned(CircularBuffer_len_read_assign_1_reg_1614));
    i_3_fu_833_p2 <= std_logic_vector(unsigned(i_2_fu_821_p2) + unsigned(ap_const_lv32_3C));
    i_4_fu_839_p3 <= 
        i_3_fu_833_p2 when (tmp_26_fu_825_p3(0) = '1') else 
        i_2_fu_821_p2;
    i_5_fu_852_p2 <= std_logic_vector(unsigned(CircularBuffer_head_i_read_ass_reg_1622) - unsigned(CircularBuffer_len_write_assig_reg_1632));
    i_6_fu_864_p2 <= std_logic_vector(unsigned(i_5_fu_852_p2) + unsigned(ap_const_lv32_3C));
    i_7_fu_870_p3 <= 
        i_6_fu_864_p2 when (tmp_27_fu_856_p3(0) = '1') else 
        i_5_fu_852_p2;
    i_8_fu_1146_p2 <= std_logic_vector(unsigned(CircularBuffer_head_i_read_ass_1_reg_1717) - unsigned(CircularBuffer_len_read_assign_3_reg_1709));
    i_9_fu_1158_p2 <= std_logic_vector(unsigned(i_8_fu_1146_p2) + unsigned(ap_const_lv32_3C));
    i_fu_605_p2 <= std_logic_vector(unsigned(p_tmp_i_reg_1554) + unsigned(ap_const_lv32_FFFFFFFF));
    last_sample_is_A_V_load_load_fu_1285_p1 <= last_sample_is_A_V;
    last_sample_is_V_V_load_load_fu_960_p1 <= last_sample_is_V_V;
    last_sample_is_V_V_loc_2_not_fu_1341_p2 <= (last_sample_is_V_V_loc_2_reg_356 xor ap_const_lv1_1);
    not_tmp_i_i1_fu_1213_p2 <= "0" when (CircularBuffer_len_read_assign_3_reg_1709 = ap_const_lv32_0) else "1";
    not_tmp_i_i2_fu_1208_p2 <= "0" when (CircularBuffer_len_write_assig_2_reg_1727 = ap_const_lv32_0) else "1";
    not_tmp_i_i4_fu_883_p2 <= "0" when (CircularBuffer_len_write_assig_reg_1632 = ap_const_lv32_0) else "1";
    not_tmp_i_i_fu_888_p2 <= "0" when (CircularBuffer_len_read_assign_1_reg_1614 = ap_const_lv32_0) else "1";
    or_cond1_fu_1407_p2 <= (tmp_21_fu_1401_p2 and tmp_22_reg_1770);
    or_cond3_fu_1456_p2 <= (tmp1_fu_1451_p2 and tmp_23_fu_1433_p2);
    or_cond_fu_1301_p2 <= (tmp_17_fu_1289_p2 and tmp_18_fu_1295_p2);
        p_1_cast_fu_1029_p1 <= std_logic_vector(resize(signed(p_1_fu_1021_p3),32));

    p_1_fu_1021_p3 <= 
        datapointA_1_fu_1015_p2 when (tmp_11_fu_1009_p2(0) = '1') else 
        datapointA_cast_fu_1001_p1;
    p_2_fu_1359_p3 <= 
        ap_const_lv13_1000 when (tmp_19_reg_407(0) = '1') else 
        ap_const_lv13_0;
        p_cast_fu_686_p1 <= std_logic_vector(resize(signed(p_s_fu_678_p3),32));

    p_i_fu_623_p3 <= 
        i_1_fu_618_p2 when (tmp_fu_610_p3(0) = '1') else 
        i_fu_605_p2;
    p_s_fu_678_p3 <= 
        datapointV_1_fu_672_p2 when (tmp_9_fu_666_p2(0) = '1') else 
        datapointV_cast_fu_658_p1;
    p_tmp_i_fu_585_p3 <= 
        ap_const_lv32_0 when (tmp_40_i_fu_579_p2(0) = '1') else 
        tmp_39_i_fu_574_p2;

    recentABools_data_address0_assign_proc : process(ap_sig_cseq_ST_st8_fsm_7, recentABools_data_addr_reg_1687, ap_sig_cseq_ST_st10_fsm_9, ap_sig_cseq_ST_st11_fsm_10, tmp_i4_7_fu_989_p1, tmp_28_i_i1_fu_1172_p1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9)) then 
            recentABools_data_address0 <= recentABools_data_addr_reg_1687;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10)) then 
            recentABools_data_address0 <= tmp_28_i_i1_fu_1172_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7)) then 
            recentABools_data_address0 <= tmp_i4_7_fu_989_p1(6 - 1 downto 0);
        else 
            recentABools_data_address0 <= "XXXXXX";
        end if; 
    end process;

    recentABools_data_address1 <= tmp_28_i_i2_fu_1203_p1(6 - 1 downto 0);

    recentABools_data_ce0_assign_proc : process(ap_sig_cseq_ST_st8_fsm_7, ap_sig_cseq_ST_st10_fsm_9, ap_sig_cseq_ST_st11_fsm_10)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) or (ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9) or (ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10))) then 
            recentABools_data_ce0 <= ap_const_logic_1;
        else 
            recentABools_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    recentABools_data_ce1_assign_proc : process(ap_sig_cseq_ST_st11_fsm_10)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10)) then 
            recentABools_data_ce1 <= ap_const_logic_1;
        else 
            recentABools_data_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    recentABools_data_we0_assign_proc : process(ap_sig_cseq_ST_st10_fsm_9)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9))) then 
            recentABools_data_we0 <= ap_const_logic_1;
        else 
            recentABools_data_we0 <= ap_const_logic_0;
        end if; 
    end process;


    recentABools_len_new_phi_fu_386_p4_assign_proc : process(tmp_13_reg_1723, ap_sig_cseq_ST_st13_fsm_12, CircularBuffer_len_write_assig_3_fu_1247_p2, recentABools_len_new_reg_383)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = tmp_13_reg_1723)))) then 
            recentABools_len_new_phi_fu_386_p4 <= CircularBuffer_len_write_assig_3_fu_1247_p2;
        else 
            recentABools_len_new_phi_fu_386_p4 <= recentABools_len_new_reg_383;
        end if; 
    end process;


    recentVBools_data_address0_assign_proc : process(ap_sig_cseq_ST_st3_fsm_2, recentVBools_data_addr_reg_1571, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st6_fsm_5, tmp_i2_5_fu_640_p1, tmp_28_i_i_fu_847_p1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
            recentVBools_data_address0 <= recentVBools_data_addr_reg_1571;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5)) then 
            recentVBools_data_address0 <= tmp_28_i_i_fu_847_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
            recentVBools_data_address0 <= tmp_i2_5_fu_640_p1(6 - 1 downto 0);
        else 
            recentVBools_data_address0 <= "XXXXXX";
        end if; 
    end process;

    recentVBools_data_address1 <= tmp_28_i_i9_fu_878_p1(6 - 1 downto 0);

    recentVBools_data_ce0_assign_proc : process(ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st6_fsm_5)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5))) then 
            recentVBools_data_ce0 <= ap_const_logic_1;
        else 
            recentVBools_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    recentVBools_data_ce1_assign_proc : process(ap_sig_cseq_ST_st6_fsm_5)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5)) then 
            recentVBools_data_ce1 <= ap_const_logic_1;
        else 
            recentVBools_data_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    recentVBools_data_we0_assign_proc : process(ap_sig_cseq_ST_st5_fsm_4)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4))) then 
            recentVBools_data_we0 <= ap_const_logic_1;
        else 
            recentVBools_data_we0 <= ap_const_logic_0;
        end if; 
    end process;


    recentVBools_len_new_phi_fu_318_p4_assign_proc : process(tmp_8_reg_1628, ap_sig_cseq_ST_st8_fsm_7, CircularBuffer_len_write_assig_1_fu_922_p2, recentVBools_len_new_reg_315)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = tmp_8_reg_1628)))) then 
            recentVBools_len_new_phi_fu_318_p4 <= CircularBuffer_len_write_assig_1_fu_922_p2;
        else 
            recentVBools_len_new_phi_fu_318_p4 <= recentVBools_len_new_reg_315;
        end if; 
    end process;


    recentdatapoints_data_address0_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, recentdatapoints_data_addr_reg_1531, ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7, tmp_i_4_fu_484_p1, tmp_41_i_fu_631_p1, tmp_i3_6_fu_981_p1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
            recentdatapoints_data_address0 <= recentdatapoints_data_addr_reg_1531;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7)) then 
            recentdatapoints_data_address0 <= tmp_i3_6_fu_981_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
            recentdatapoints_data_address0 <= tmp_41_i_fu_631_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) then 
            recentdatapoints_data_address0 <= tmp_i_4_fu_484_p1(3 - 1 downto 0);
        else 
            recentdatapoints_data_address0 <= "XXX";
        end if; 
    end process;


    recentdatapoints_data_ce0_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0, ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0))) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) or (ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
            recentdatapoints_data_ce0 <= ap_const_logic_1;
        else 
            recentdatapoints_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    recentdatapoints_data_we0_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            recentdatapoints_data_we0 <= ap_const_logic_1;
        else 
            recentdatapoints_data_we0 <= ap_const_logic_0;
        end if; 
    end process;

    recentdatapoints_len_load_op_fu_554_p2 <= std_logic_vector(unsigned(recentdatapoints_len) + unsigned(ap_const_lv32_1));
    recentdatapoints_sum_loc_i_fu_541_p3 <= 
        tmp_35_i_fu_535_p2 when (tmp_i_fu_521_p2(0) = '1') else 
        recentdatapoints_sum;
    reset_params_V_read_read_fu_178_p2 <= reset_params_V;
    sel_tmp1_fu_1373_p3 <= 
        p_2_fu_1359_p3 when (sel_tmp_fu_1367_p2(0) = '1') else 
        ap_const_lv13_0;
    sel_tmp2_fu_1387_p2 <= (last_sample_is_V_V_loc_2_reg_356 and tmp_21_not_not_fu_1381_p2);
    sel_tmp_fu_1367_p2 <= (brmerge_fu_1347_p2 and tmp_20_fu_1353_p2);

    sum_1_phi_fu_377_p4_assign_proc : process(tmp_13_reg_1723, ap_sig_cseq_ST_st13_fsm_12, CircularBuffer_sum_write_assig_3_fu_1240_p2, sum_1_reg_374)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = tmp_13_reg_1723)))) then 
            sum_1_phi_fu_377_p4 <= CircularBuffer_sum_write_assig_3_fu_1240_p2;
        else 
            sum_1_phi_fu_377_p4 <= sum_1_reg_374;
        end if; 
    end process;


    sum_phi_fu_309_p4_assign_proc : process(tmp_8_reg_1628, ap_sig_cseq_ST_st8_fsm_7, CircularBuffer_sum_write_assig_1_fu_915_p2, sum_reg_306)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = tmp_8_reg_1628)))) then 
            sum_phi_fu_309_p4 <= CircularBuffer_sum_write_assig_1_fu_915_p2;
        else 
            sum_phi_fu_309_p4 <= sum_reg_306;
        end if; 
    end process;

    tmp1_fu_1451_p2 <= (tmp_24_fu_1439_p2 and tmp_25_reg_1775);
    tmp_10_fu_942_p2 <= "1" when (signed(sum_phi_fu_309_p4) > signed(tmp_2_fu_938_p1)) else "0";
    tmp_11_fu_1009_p2 <= "1" when (aflip = ap_const_lv8_FF) else "0";
    tmp_12_fu_1037_p2 <= "1" when (signed(p_1_cast_fu_1029_p1) > signed(a_thresh)) else "0";
    tmp_13_fu_1122_p2 <= "1" when (signed(CircularBuffer_len_read_assign_3_fu_1089_p3) > signed(ACaptureThresh_loc_reg_286)) else "0";
    tmp_14_fu_1253_p4 <= ACaptureThresh_loc_reg_286(31 downto 1);
        tmp_15_fu_1263_p1 <= std_logic_vector(resize(signed(tmp_14_fu_1253_p4),32));

    tmp_16_fu_1267_p2 <= "1" when (signed(sum_1_phi_fu_377_p4) > signed(tmp_15_fu_1263_p1)) else "0";
    tmp_17_fu_1289_p2 <= "1" when (signed(VbeatDelay_new_1_reg_324) > signed(VbeatFallDelay_new_1_reg_340)) else "0";
    tmp_18_fu_1295_p2 <= "1" when (signed(VbeatFallDelay_new_1_reg_340) > signed(ap_const_lv32_3E)) else "0";
    tmp_1_fu_928_p4 <= VCaptureThresh_loc_reg_296(31 downto 1);
    tmp_20_fu_1353_p2 <= "1" when (AbeatDelay_new_reg_392 = ap_const_lv32_0) else "0";
    tmp_21_fu_1401_p2 <= "1" when (signed(AbeatDelay_new_reg_392) > signed(ap_const_lv32_FA)) else "0";
    tmp_21_not_fu_1335_p2 <= "0" when (VbeatDelay_new_1_reg_324 = ap_const_lv32_0) else "1";
    tmp_21_not_not_fu_1381_p2 <= (tmp_21_not_fu_1335_p2 xor ap_const_lv1_1);
    tmp_22_fu_1319_p2 <= "1" when (signed(tmp_6_reg_1536) > signed(ACaptureThresh_loc_reg_286)) else "0";
    tmp_23_fu_1433_p2 <= "1" when (signed(VbeatDelay_new_1_reg_324) > signed(AbeatDelay_new_reg_392)) else "0";
    tmp_24_fu_1439_p2 <= "1" when (signed(AbeatDelay_new_reg_392) > signed(ap_const_lv32_3E)) else "0";
    tmp_25_fu_1324_p2 <= "1" when (signed(tmp_7_reg_1542) > signed(VCaptureThresh_loc_reg_296)) else "0";
    tmp_26_fu_825_p3 <= i_2_fu_821_p2(31 downto 31);
    tmp_27_fu_856_p3 <= i_5_fu_852_p2(31 downto 31);
    tmp_28_fu_1150_p3 <= i_8_fu_1146_p2(31 downto 31);
        tmp_28_i_i1_fu_1172_p1 <= std_logic_vector(resize(signed(i_10_fu_1164_p3),64));

        tmp_28_i_i2_fu_1203_p1 <= std_logic_vector(resize(signed(i_13_fu_1195_p3),64));

        tmp_28_i_i9_fu_878_p1 <= std_logic_vector(resize(signed(i_7_fu_870_p3),64));

        tmp_28_i_i_fu_847_p1 <= std_logic_vector(resize(signed(i_4_fu_839_p3),64));

    tmp_29_fu_1181_p3 <= i_11_fu_1177_p2(31 downto 31);
    tmp_29_i1_fu_1063_p2 <= std_logic_vector(unsigned(recentABools_sum) - unsigned(extLd2_fu_1060_p1));
    tmp_29_i_fu_750_p2 <= std_logic_vector(unsigned(recentVBools_sum) - unsigned(extLd1_fu_747_p1));
        tmp_2_fu_938_p1 <= std_logic_vector(resize(signed(tmp_1_fu_928_p4),32));

    tmp_33_i1_fu_1097_p2 <= std_logic_vector(unsigned(recentABools_head_i) + unsigned(ap_const_lv32_1));
    tmp_33_i_fu_784_p2 <= std_logic_vector(unsigned(recentVBools_head_i) + unsigned(ap_const_lv32_1));
    tmp_34_i1_fu_1102_p2 <= "1" when (tmp_33_i1_fu_1097_p2 = ap_const_lv32_3C) else "0";
    tmp_34_i_fu_789_p2 <= "1" when (tmp_33_i_fu_784_p2 = ap_const_lv32_3C) else "0";
    tmp_35_i_fu_535_p2 <= std_logic_vector(unsigned(recentdatapoints_sum) - unsigned(extLd_fu_531_p1));
    tmp_37_i_fu_549_p2 <= std_logic_vector(unsigned(recentdatapoints_sum_loc_i_fu_541_p3) + unsigned(val_assign_reg_1511));
    tmp_38_i_fu_560_p3 <= 
        ap_const_lv32_5 when (tmp_i_fu_521_p2(0) = '1') else 
        recentdatapoints_len_load_op_fu_554_p2;
    tmp_39_i_fu_574_p2 <= std_logic_vector(unsigned(recentdatapoints_head_i) + unsigned(ap_const_lv32_1));
    tmp_3_fu_704_p2 <= std_logic_vector(unsigned(AbeatDelay) + unsigned(ap_const_lv32_1));
    tmp_40_i_fu_579_p2 <= "1" when (tmp_39_i_fu_574_p2 = ap_const_lv32_5) else "0";
        tmp_41_i_fu_631_p1 <= std_logic_vector(resize(signed(p_i_fu_623_p3),64));

    tmp_4_fu_714_p2 <= std_logic_vector(unsigned(VbeatDelay) + unsigned(ap_const_lv32_1));
    tmp_5_fu_724_p2 <= std_logic_vector(unsigned(VbeatFallDelay) + unsigned(ap_const_lv32_1));
    tmp_6_fu_495_p3 <= 
        ap_const_lv32_1 when (reset_A_V(0) = '1') else 
        AstimDelay_load_op_fu_489_p2;
    tmp_7_fu_509_p3 <= 
        ap_const_lv32_1 when (reset_V_V(0) = '1') else 
        VstimDelay_load_op_fu_503_p2;
    tmp_8_fu_809_p2 <= "1" when (signed(CircularBuffer_len_read_assign_1_fu_776_p3) > signed(VCaptureThresh_loc_reg_296)) else "0";
    tmp_9_fu_666_p2 <= "1" when (vflip = ap_const_lv8_FF) else "0";
    tmp_fu_610_p3 <= i_fu_605_p2(31 downto 31);
    tmp_i1_fu_645_p2 <= "1" when (tmp_38_i_reg_1548 = ap_const_lv32_0) else "0";
        tmp_i2_5_fu_640_p1 <= std_logic_vector(resize(signed(recentVBools_head_i),64));

    tmp_i2_fu_741_p2 <= "1" when (recentVBools_len = ap_const_lv32_3C) else "0";
        tmp_i3_6_fu_981_p1 <= std_logic_vector(resize(signed(p_tmp_i_reg_1554),64));

    tmp_i3_fu_976_p2 <= "1" when (tmp_38_i_reg_1548 = ap_const_lv32_5) else "0";
        tmp_i4_7_fu_989_p1 <= std_logic_vector(resize(signed(recentABools_head_i),64));

    tmp_i4_fu_1054_p2 <= "1" when (recentABools_len = ap_const_lv32_3C) else "0";
        tmp_i_4_fu_484_p1 <= std_logic_vector(resize(signed(recentdatapoints_head_i),64));

    tmp_i_fu_521_p2 <= "1" when (recentdatapoints_len = ap_const_lv32_5) else "0";
    tmp_s_fu_694_p2 <= "1" when (signed(p_cast_fu_686_p1) > signed(v_thresh)) else "0";
    toReturn_1_fu_1393_p3 <= 
        ap_const_lv13_F0 when (sel_tmp2_fu_1387_p2(0) = '1') else 
        sel_tmp1_fu_1373_p3;
    toReturn_2_fu_1425_p3 <= 
        toReturn_fu_1412_p2 when (or_cond1_fu_1407_p2(0) = '1') else 
        toReturn_1_fu_1393_p3;
    toReturn_3_fu_1475_p3 <= 
        toReturn_4_fu_1462_p2 when (or_cond3_fu_1456_p2(0) = '1') else 
        toReturn_2_fu_1425_p3;
    toReturn_4_fu_1462_p2 <= (toReturn_2_fu_1425_p3 or ap_const_lv13_F);
    toReturn_5_fu_893_p2 <= (recentVBools_data_q0 and not_tmp_i_i_fu_888_p2);
    toReturn_6_fu_899_p2 <= (recentVBools_data_q1 and not_tmp_i_i4_reg_1648);
    toReturn_7_fu_1218_p2 <= (recentABools_data_q0 and not_tmp_i_i1_fu_1213_p2);
    toReturn_8_fu_1224_p2 <= (recentABools_data_q1 and not_tmp_i_i2_reg_1743);
    toReturn_fu_1412_p2 <= (toReturn_1_fu_1393_p3 or ap_const_lv13_F00);
    toReturn_i12_cast_fu_912_p1 <= std_logic_vector(resize(unsigned(toReturn_6_reg_1658),32));
    toReturn_i25_cast_fu_1229_p1 <= std_logic_vector(resize(unsigned(toReturn_7_reg_1748),32));
    toReturn_i38_cast_fu_1237_p1 <= std_logic_vector(resize(unsigned(toReturn_8_reg_1753),32));
    toReturn_i_cast_fu_904_p1 <= std_logic_vector(resize(unsigned(toReturn_5_reg_1653),32));
    val_assign_1_fu_730_p1 <= std_logic_vector(resize(unsigned(tmp_s_reg_1576),32));
    val_assign_2_fu_1043_p1 <= std_logic_vector(resize(unsigned(tmp_12_reg_1692),32));
        val_assign_fu_424_p1 <= std_logic_vector(resize(signed(data),32));

end behav;
