-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Decision is
generic (
    C_S_AXI_AXILITES_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_AXILITES_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_AXILiteS_AWVALID : IN STD_LOGIC;
    s_axi_AXILiteS_AWREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_WVALID : IN STD_LOGIC;
    s_axi_AXILiteS_WREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH/8-1 downto 0);
    s_axi_AXILiteS_ARVALID : IN STD_LOGIC;
    s_axi_AXILiteS_ARREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_RVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_RREADY : IN STD_LOGIC;
    s_axi_AXILiteS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_AXILiteS_BVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_BREADY : IN STD_LOGIC;
    s_axi_AXILiteS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of Decision is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Decision,hls_ip_2016_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.640000,HLS_SYN_LAT=11,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1767,HLS_SYN_LUT=2997}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_st6_fsm_5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_st7_fsm_6 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_st8_fsm_7 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_st9_fsm_8 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_st10_fsm_9 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_st11_fsm_10 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_st12_fsm_11 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_st13_fsm_12 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_st14_fsm_13 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_FFFFFFFE : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111110";
    constant ap_const_lv32_FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111010";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_F0 : STD_LOGIC_VECTOR (12 downto 0) := "0000011110000";
    constant ap_const_lv32_3E8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111101000";
    constant ap_const_lv13_F00 : STD_LOGIC_VECTOR (12 downto 0) := "0111100000000";
    constant ap_const_lv32_384 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001110000100";
    constant ap_const_lv13_F : STD_LOGIC_VECTOR (12 downto 0) := "0000000001111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_31 : BOOLEAN;
    signal ap_ready : STD_LOGIC;
    signal reset_A_V : STD_LOGIC_VECTOR (0 downto 0);
    signal reset_V_V : STD_LOGIC_VECTOR (0 downto 0);
    signal reset_params_V : STD_LOGIC_VECTOR (0 downto 0);
    signal athresh : STD_LOGIC_VECTOR (31 downto 0);
    signal vthresh : STD_LOGIC_VECTOR (31 downto 0);
    signal a_flip : STD_LOGIC_VECTOR (7 downto 0);
    signal v_flip : STD_LOGIC_VECTOR (7 downto 0);
    signal a_length : STD_LOGIC_VECTOR (31 downto 0);
    signal v_length : STD_LOGIC_VECTOR (31 downto 0);
    signal data : STD_LOGIC_VECTOR (15 downto 0);
    signal AstimDelay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal VstimDelay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ACaptureThresh : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    signal VCaptureThresh : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    signal v_thresh : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal a_thresh : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal aflip : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal vflip : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal recentdatapoints_len : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentdatapoints_head_i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentdatapoints_sum : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentdatapoints_data_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal recentdatapoints_data_ce0 : STD_LOGIC;
    signal recentdatapoints_data_we0 : STD_LOGIC;
    signal recentdatapoints_data_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal AbeatDelay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal VbeatDelay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal VbeatFallDelay : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentVBools_sum : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentVBools_head_i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentVBools_len : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentVBools_data_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal recentVBools_data_ce0 : STD_LOGIC;
    signal recentVBools_data_we0 : STD_LOGIC;
    signal recentVBools_data_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal recentVBools_data_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal recentVBools_data_ce1 : STD_LOGIC;
    signal recentVBools_data_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_sample_is_V_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal recentABools_sum : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentABools_head_i : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentABools_len : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal recentABools_data_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal recentABools_data_ce0 : STD_LOGIC;
    signal recentABools_data_we0 : STD_LOGIC;
    signal recentABools_data_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal recentABools_data_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal recentABools_data_ce1 : STD_LOGIC;
    signal recentABools_data_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_sample_is_A_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal data_read_reg_1495 : STD_LOGIC_VECTOR (15 downto 0);
    signal val_assign_fu_426_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_assign_reg_1513 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentdatapoints_data_addr_reg_1533 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_6_fu_497_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_reg_1538 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_511_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_reg_1544 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_38_i_fu_562_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_38_i_reg_1550 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_176 : BOOLEAN;
    signal p_tmp_i_fu_587_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_tmp_i_reg_1556 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_187 : BOOLEAN;
    signal recentVBools_data_addr_reg_1573 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1578 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_200 : BOOLEAN;
    signal recentVBools_data_load_reg_1584 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_706_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_reg_1589 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st5_fsm_4 : STD_LOGIC;
    signal ap_sig_210 : BOOLEAN;
    signal tmp_4_fu_716_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_reg_1596 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_726_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_reg_1603 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_read_assign_fu_766_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_read_assign_reg_1610 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_read_assign_1_fu_778_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_read_assign_1_reg_1616 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_head_i_read_ass_fu_797_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_head_i_read_ass_reg_1624 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_1630 : STD_LOGIC_VECTOR (0 downto 0);
    signal CircularBuffer_len_write_assig_fu_817_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_write_assig_reg_1634 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st6_fsm_5 : STD_LOGIC;
    signal ap_sig_236 : BOOLEAN;
    signal not_tmp_i_i4_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_i_i4_reg_1650 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_5_fu_895_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_5_reg_1655 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st7_fsm_6 : STD_LOGIC;
    signal ap_sig_249 : BOOLEAN;
    signal toReturn_6_fu_901_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_6_reg_1660 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_sample_is_V_V_load_load_fu_962_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st8_fsm_7 : STD_LOGIC;
    signal ap_sig_260 : BOOLEAN;
    signal tmp_i3_fu_978_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i3_reg_1674 : STD_LOGIC_VECTOR (0 downto 0);
    signal recentABools_data_addr_reg_1689 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_12_fu_1039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1694 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st9_fsm_8 : STD_LOGIC;
    signal ap_sig_276 : BOOLEAN;
    signal recentABools_data_load_reg_1700 : STD_LOGIC_VECTOR (0 downto 0);
    signal CircularBuffer_sum_read_assign_1_fu_1079_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_read_assign_1_reg_1705 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st10_fsm_9 : STD_LOGIC;
    signal ap_sig_286 : BOOLEAN;
    signal CircularBuffer_len_read_assign_3_fu_1091_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_read_assign_3_reg_1711 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_head_i_read_ass_1_fu_1110_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_head_i_read_ass_1_reg_1719 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_1124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_1725 : STD_LOGIC_VECTOR (0 downto 0);
    signal CircularBuffer_len_write_assig_2_fu_1142_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_write_assig_2_reg_1729 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st11_fsm_10 : STD_LOGIC;
    signal ap_sig_306 : BOOLEAN;
    signal not_tmp_i_i2_fu_1210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_tmp_i_i2_reg_1745 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_7_fu_1220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_7_reg_1750 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st12_fsm_11 : STD_LOGIC;
    signal ap_sig_319 : BOOLEAN;
    signal toReturn_8_fu_1226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_8_reg_1755 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_sample_is_A_V_load_load_fu_1287_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st13_fsm_12 : STD_LOGIC;
    signal ap_sig_330 : BOOLEAN;
    signal tmp_22_fu_1321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_1772 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_1326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_reg_1777 : STD_LOGIC_VECTOR (0 downto 0);
    signal ACaptureThresh_loc_reg_288 : STD_LOGIC_VECTOR (31 downto 0);
    signal reset_params_V_read_read_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal VCaptureThresh_loc_reg_298 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_write_assig_1_fu_917_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_phi_fu_311_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_reg_308 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_write_assig_1_fu_924_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentVBools_len_new_phi_fu_320_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentVBools_len_new_reg_317 : STD_LOGIC_VECTOR (31 downto 0);
    signal VbeatDelay_new_1_reg_326 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_944_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal VbeatFallDelay_new_1_reg_342 : STD_LOGIC_VECTOR (31 downto 0);
    signal last_sample_is_V_V_loc_2_reg_358 : STD_LOGIC_VECTOR (0 downto 0);
    signal CircularBuffer_sum_write_assig_3_fu_1242_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_phi_fu_379_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_1_reg_376 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_write_assig_3_fu_1249_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentABools_len_new_phi_fu_388_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentABools_len_new_reg_385 : STD_LOGIC_VECTOR (31 downto 0);
    signal AbeatDelay_new_reg_394 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_16_fu_1269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_1303_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_409 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_7_fu_486_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_41_i_fu_633_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_i2_8_fu_642_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_28_i_i_fu_849_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_28_i_i9_fu_880_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_i3_9_fu_983_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_i4_10_fu_991_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_28_i_i1_fu_1174_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_28_i_i2_fu_1205_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal AstimDelay_new_fu_1420_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st14_fsm_13 : STD_LOGIC;
    signal ap_sig_433 : BOOLEAN;
    signal VstimDelay_new_fu_1470_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_37_i_fu_551_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal AstimDelay_load_op_fu_491_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal VstimDelay_load_op_fu_505_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal extLd_fu_533_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_i_fu_537_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentdatapoints_sum_loc_i_fu_543_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal recentdatapoints_len_load_op_fu_556_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_39_i_fu_576_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_40_i_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_607_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_612_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_fu_620_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_i_fu_625_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i1_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal datapointV_fu_652_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal datapointV_cast_fu_660_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_9_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal datapointV_1_fu_674_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_s_fu_680_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_cast_fu_688_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal extLd1_fu_749_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i2_fu_743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_i_fu_752_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_int_30_sum_i_fu_758_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_assign_1_fu_732_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_read_assign_fu_772_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_33_i_fu_786_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_34_i_fu_791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_2_fu_823_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_26_fu_827_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_3_fu_835_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_4_fu_841_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_5_fu_854_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_27_fu_858_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_6_fu_866_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_7_fu_872_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal not_tmp_i_i_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_i_cast_fu_906_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_write_assig_fu_909_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal toReturn_i12_cast_fu_914_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_930_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_2_fu_940_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal datapointA_fu_996_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal datapointA_cast_fu_1003_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_11_fu_1011_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal datapointA_1_fu_1017_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_1_fu_1023_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_1_cast_fu_1031_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal extLd2_fu_1062_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i4_fu_1056_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_i1_fu_1065_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_int_30_sum_i1_fu_1071_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_assign_2_fu_1045_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_len_read_assign_2_fu_1085_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_33_i1_fu_1099_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_34_i1_fu_1104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_8_fu_1148_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_28_fu_1152_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_9_fu_1160_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_10_fu_1166_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_11_fu_1179_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_fu_1183_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_12_fu_1191_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_13_fu_1197_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal not_tmp_i_i1_fu_1215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_i25_cast_fu_1231_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal CircularBuffer_sum_write_assig_2_fu_1234_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal toReturn_i38_cast_fu_1239_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_1255_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_15_fu_1265_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_1291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_1297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_not_fu_1337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_sample_is_V_V_loc_2_not_fu_1343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_fu_1349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_1355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_1369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_2_fu_1361_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_21_not_not_fu_1383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_1389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_1375_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_21_fu_1403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_1_fu_1395_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_cond1_fu_1409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_fu_1414_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_24_fu_1441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_1453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_1435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_2_fu_1427_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal or_cond3_fu_1458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal toReturn_4_fu_1464_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal toReturn_3_fu_1477_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_sig_151 : BOOLEAN;
    signal ap_sig_408 : BOOLEAN;
    signal ap_sig_404 : BOOLEAN;
    signal ap_sig_367 : BOOLEAN;
    signal ap_sig_365 : BOOLEAN;

    component Decision_recentdatapoints_data IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component Decision_recentVBools_data IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component Decision_AXILiteS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_return : IN STD_LOGIC_VECTOR (15 downto 0);
        reset_A_V : OUT STD_LOGIC_VECTOR (0 downto 0);
        reset_V_V : OUT STD_LOGIC_VECTOR (0 downto 0);
        reset_params_V : OUT STD_LOGIC_VECTOR (0 downto 0);
        athresh : OUT STD_LOGIC_VECTOR (31 downto 0);
        vthresh : OUT STD_LOGIC_VECTOR (31 downto 0);
        a_flip : OUT STD_LOGIC_VECTOR (7 downto 0);
        v_flip : OUT STD_LOGIC_VECTOR (7 downto 0);
        a_length : OUT STD_LOGIC_VECTOR (31 downto 0);
        v_length : OUT STD_LOGIC_VECTOR (31 downto 0);
        data : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    recentdatapoints_data_U : component Decision_recentdatapoints_data
    generic map (
        DataWidth => 16,
        AddressRange => 20,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => recentdatapoints_data_address0,
        ce0 => recentdatapoints_data_ce0,
        we0 => recentdatapoints_data_we0,
        d0 => data_read_reg_1495,
        q0 => recentdatapoints_data_q0);

    recentVBools_data_U : component Decision_recentVBools_data
    generic map (
        DataWidth => 1,
        AddressRange => 30,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => recentVBools_data_address0,
        ce0 => recentVBools_data_ce0,
        we0 => recentVBools_data_we0,
        d0 => tmp_s_reg_1578,
        q0 => recentVBools_data_q0,
        address1 => recentVBools_data_address1,
        ce1 => recentVBools_data_ce1,
        q1 => recentVBools_data_q1);

    recentABools_data_U : component Decision_recentVBools_data
    generic map (
        DataWidth => 1,
        AddressRange => 30,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => recentABools_data_address0,
        ce0 => recentABools_data_ce0,
        we0 => recentABools_data_we0,
        d0 => tmp_12_reg_1694,
        q0 => recentABools_data_q0,
        address1 => recentABools_data_address1,
        ce1 => recentABools_data_ce1,
        q1 => recentABools_data_q1);

    Decision_AXILiteS_s_axi_U : component Decision_AXILiteS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_AXILITES_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_AXILITES_DATA_WIDTH)
    port map (
        AWVALID => s_axi_AXILiteS_AWVALID,
        AWREADY => s_axi_AXILiteS_AWREADY,
        AWADDR => s_axi_AXILiteS_AWADDR,
        WVALID => s_axi_AXILiteS_WVALID,
        WREADY => s_axi_AXILiteS_WREADY,
        WDATA => s_axi_AXILiteS_WDATA,
        WSTRB => s_axi_AXILiteS_WSTRB,
        ARVALID => s_axi_AXILiteS_ARVALID,
        ARREADY => s_axi_AXILiteS_ARREADY,
        ARADDR => s_axi_AXILiteS_ARADDR,
        RVALID => s_axi_AXILiteS_RVALID,
        RREADY => s_axi_AXILiteS_RREADY,
        RDATA => s_axi_AXILiteS_RDATA,
        RRESP => s_axi_AXILiteS_RRESP,
        BVALID => s_axi_AXILiteS_BVALID,
        BREADY => s_axi_AXILiteS_BREADY,
        BRESP => s_axi_AXILiteS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        ap_return => ap_return,
        reset_A_V => reset_A_V,
        reset_V_V => reset_V_V,
        reset_params_V => reset_params_V,
        athresh => athresh,
        vthresh => vthresh,
        a_flip => a_flip,
        v_flip => v_flip,
        a_length => a_length,
        v_length => v_length,
        data => data);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ACaptureThresh_loc_reg_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_151) then
                if ((ap_const_lv1_0 = reset_params_V_read_read_fu_180_p2)) then 
                    ACaptureThresh_loc_reg_288 <= ACaptureThresh;
                elsif (not((ap_const_lv1_0 = reset_params_V_read_read_fu_180_p2))) then 
                    ACaptureThresh_loc_reg_288 <= a_length;
                end if;
            end if; 
        end if;
    end process;

    AbeatDelay_new_reg_394_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and (ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1) and not((ap_const_lv1_0 = tmp_16_fu_1269_p2)) and not((ap_const_lv1_0 = or_cond_fu_1303_p2)))) then 
                AbeatDelay_new_reg_394 <= ap_const_lv32_0;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1)) and not((ap_const_lv1_0 = tmp_16_fu_1269_p2)) and not((ap_const_lv1_0 = or_cond_fu_1303_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and ((not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1)) and (ap_const_lv1_0 = tmp_16_fu_1269_p2)) or (not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1)) and (ap_const_lv1_0 = or_cond_fu_1303_p2)))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and (((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1) and (ap_const_lv1_0 = tmp_16_fu_1269_p2)) or ((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1) and (ap_const_lv1_0 = or_cond_fu_1303_p2)))))) then 
                AbeatDelay_new_reg_394 <= tmp_3_reg_1589;
            end if; 
        end if;
    end process;

    VCaptureThresh_loc_reg_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_151) then
                if ((ap_const_lv1_0 = reset_params_V_read_read_fu_180_p2)) then 
                    VCaptureThresh_loc_reg_298 <= VCaptureThresh;
                elsif (not((ap_const_lv1_0 = reset_params_V_read_read_fu_180_p2))) then 
                    VCaptureThresh_loc_reg_298 <= v_length;
                end if;
            end if; 
        end if;
    end process;

    VbeatDelay_new_1_reg_326_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1) and not((ap_const_lv1_0 = tmp_10_fu_944_p2)))) then 
                VbeatDelay_new_1_reg_326 <= ap_const_lv32_0;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1)) and not((ap_const_lv1_0 = tmp_10_fu_944_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1)) and (ap_const_lv1_0 = tmp_10_fu_944_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1) and (ap_const_lv1_0 = tmp_10_fu_944_p2)))) then 
                VbeatDelay_new_1_reg_326 <= tmp_4_reg_1596;
            end if; 
        end if;
    end process;

    VbeatFallDelay_new_1_reg_342_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1)) and (ap_const_lv1_0 = tmp_10_fu_944_p2))) then 
                VbeatFallDelay_new_1_reg_342 <= ap_const_lv32_0;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1)) and not((ap_const_lv1_0 = tmp_10_fu_944_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1) and not((ap_const_lv1_0 = tmp_10_fu_944_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1) and (ap_const_lv1_0 = tmp_10_fu_944_p2)))) then 
                VbeatFallDelay_new_1_reg_342 <= tmp_5_reg_1603;
            end if; 
        end if;
    end process;

    last_sample_is_A_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12)) then
                if (ap_sig_404) then 
                    last_sample_is_A_V <= ap_const_lv1_1;
                elsif (ap_sig_408) then 
                    last_sample_is_A_V <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;

    last_sample_is_V_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7)) then
                if (ap_sig_365) then 
                    last_sample_is_V_V <= ap_const_lv1_1;
                elsif (ap_sig_367) then 
                    last_sample_is_V_V <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;

    last_sample_is_V_V_loc_2_reg_358_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1)) and (ap_const_lv1_0 = tmp_10_fu_944_p2))) then 
                last_sample_is_V_V_loc_2_reg_358 <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1) and not((ap_const_lv1_0 = tmp_10_fu_944_p2)))) then 
                last_sample_is_V_V_loc_2_reg_358 <= ap_const_lv1_1;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1)) and not((ap_const_lv1_0 = tmp_10_fu_944_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and (ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1) and (ap_const_lv1_0 = tmp_10_fu_944_p2)))) then 
                last_sample_is_V_V_loc_2_reg_358 <= last_sample_is_V_V;
            end if; 
        end if;
    end process;

    recentABools_len_new_reg_385_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9) and (ap_const_lv1_0 = tmp_13_fu_1124_p2))) then 
                recentABools_len_new_reg_385 <= CircularBuffer_len_read_assign_3_fu_1091_p3;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = tmp_13_reg_1725)))) then 
                recentABools_len_new_reg_385 <= CircularBuffer_len_write_assig_3_fu_1249_p2;
            end if; 
        end if;
    end process;

    recentVBools_len_new_reg_317_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and (ap_const_lv1_0 = tmp_8_fu_811_p2))) then 
                recentVBools_len_new_reg_317 <= CircularBuffer_len_read_assign_1_fu_778_p3;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = tmp_8_reg_1630)))) then 
                recentVBools_len_new_reg_317 <= CircularBuffer_len_write_assig_1_fu_924_p2;
            end if; 
        end if;
    end process;

    sum_1_reg_376_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9) and (ap_const_lv1_0 = tmp_13_fu_1124_p2))) then 
                sum_1_reg_376 <= CircularBuffer_sum_read_assign_1_fu_1079_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = tmp_13_reg_1725)))) then 
                sum_1_reg_376 <= CircularBuffer_sum_write_assig_3_fu_1242_p2;
            end if; 
        end if;
    end process;

    sum_reg_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and (ap_const_lv1_0 = tmp_8_fu_811_p2))) then 
                sum_reg_308 <= CircularBuffer_sum_read_assign_fu_766_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = tmp_8_reg_1630)))) then 
                sum_reg_308 <= CircularBuffer_sum_write_assig_1_fu_917_p2;
            end if; 
        end if;
    end process;

    tmp_19_reg_409_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and ((not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1)) and (ap_const_lv1_0 = tmp_16_fu_1269_p2)) or (not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1)) and (ap_const_lv1_0 = or_cond_fu_1303_p2))))) then 
                tmp_19_reg_409 <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and (ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1) and not((ap_const_lv1_0 = tmp_16_fu_1269_p2)) and not((ap_const_lv1_0 = or_cond_fu_1303_p2)))) then 
                tmp_19_reg_409 <= ap_const_lv1_1;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1)) and not((ap_const_lv1_0 = tmp_16_fu_1269_p2)) and not((ap_const_lv1_0 = or_cond_fu_1303_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and (((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1) and (ap_const_lv1_0 = tmp_16_fu_1269_p2)) or ((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1) and (ap_const_lv1_0 = or_cond_fu_1303_p2)))))) then 
                tmp_19_reg_409 <= last_sample_is_A_V;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)) and not((ap_const_lv1_0 = reset_params_V_read_read_fu_180_p2)))) then
                ACaptureThresh <= a_length;
                VCaptureThresh <= v_length;
                a_thresh <= athresh;
                aflip <= a_flip;
                v_thresh <= vthresh;
                vflip <= v_flip;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st14_fsm_13)) then
                AbeatDelay <= AbeatDelay_new_reg_394;
                AstimDelay <= AstimDelay_new_fu_1420_p3;
                VstimDelay <= VstimDelay_new_fu_1470_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9)) then
                CircularBuffer_head_i_read_ass_1_reg_1719 <= CircularBuffer_head_i_read_ass_1_fu_1110_p3;
                CircularBuffer_len_read_assign_3_reg_1711 <= CircularBuffer_len_read_assign_3_fu_1091_p3;
                CircularBuffer_sum_read_assign_1_reg_1705 <= CircularBuffer_sum_read_assign_1_fu_1079_p2;
                VbeatDelay <= VbeatDelay_new_1_reg_326;
                VbeatFallDelay <= VbeatFallDelay_new_1_reg_342;
                recentABools_head_i <= CircularBuffer_head_i_read_ass_1_fu_1110_p3;
                tmp_13_reg_1725 <= tmp_13_fu_1124_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then
                CircularBuffer_head_i_read_ass_reg_1624 <= CircularBuffer_head_i_read_ass_fu_797_p3;
                CircularBuffer_len_read_assign_1_reg_1616 <= CircularBuffer_len_read_assign_1_fu_778_p3;
                CircularBuffer_sum_read_assign_reg_1610 <= CircularBuffer_sum_read_assign_fu_766_p2;
                recentVBools_head_i <= CircularBuffer_head_i_read_ass_fu_797_p3;
                tmp_3_reg_1589 <= tmp_3_fu_706_p2;
                tmp_4_reg_1596 <= tmp_4_fu_716_p2;
                tmp_5_reg_1603 <= tmp_5_fu_726_p2;
                tmp_8_reg_1630 <= tmp_8_fu_811_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9) and not((ap_const_lv1_0 = tmp_13_fu_1124_p2)))) then
                CircularBuffer_len_write_assig_2_reg_1729 <= CircularBuffer_len_write_assig_2_fu_1142_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and not((ap_const_lv1_0 = tmp_8_fu_811_p2)))) then
                CircularBuffer_len_write_assig_reg_1634 <= CircularBuffer_len_write_assig_fu_817_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)))) then
                data_read_reg_1495 <= data;
                recentdatapoints_data_addr_reg_1533 <= tmp_i_7_fu_486_p1(5 - 1 downto 0);
                tmp_6_reg_1538 <= tmp_6_fu_497_p3;
                tmp_7_reg_1544 <= tmp_7_fu_511_p3;
                val_assign_reg_1513 <= val_assign_fu_426_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10)) then
                not_tmp_i_i2_reg_1745 <= not_tmp_i_i2_fu_1210_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5)) then
                not_tmp_i_i4_reg_1650 <= not_tmp_i_i4_fu_885_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then
                p_tmp_i_reg_1556 <= p_tmp_i_fu_587_p3;
                recentdatapoints_head_i <= p_tmp_i_fu_587_p3;
                recentdatapoints_len <= tmp_38_i_fu_562_p3;
                recentdatapoints_sum <= tmp_37_i_fu_551_p2;
                tmp_38_i_reg_1550 <= tmp_38_i_fu_562_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7)) then
                recentABools_data_addr_reg_1689 <= tmp_i4_10_fu_991_p1(5 - 1 downto 0);
                recentVBools_len <= recentVBools_len_new_phi_fu_320_p4;
                recentVBools_sum <= sum_phi_fu_311_p4;
                tmp_i3_reg_1674 <= tmp_i3_fu_978_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8)) then
                recentABools_data_load_reg_1700 <= recentABools_data_q0;
                tmp_12_reg_1694 <= tmp_12_fu_1039_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12)) then
                recentABools_len <= recentABools_len_new_phi_fu_388_p4;
                recentABools_sum <= sum_1_phi_fu_379_p4;
                tmp_22_reg_1772 <= tmp_22_fu_1321_p2;
                tmp_25_reg_1777 <= tmp_25_fu_1326_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then
                recentVBools_data_addr_reg_1573 <= tmp_i2_8_fu_642_p1(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then
                recentVBools_data_load_reg_1584 <= recentVBools_data_q0;
                tmp_s_reg_1578 <= tmp_s_fu_696_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6)) then
                toReturn_5_reg_1655 <= toReturn_5_fu_895_p2;
                toReturn_6_reg_1660 <= toReturn_6_fu_901_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st12_fsm_11)) then
                toReturn_7_reg_1750 <= toReturn_7_fu_1220_p2;
                toReturn_8_reg_1755 <= toReturn_8_fu_1226_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, tmp_8_fu_811_p2, tmp_13_fu_1124_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                ap_NS_fsm <= ap_ST_st3_fsm_2;
            when ap_ST_st3_fsm_2 => 
                ap_NS_fsm <= ap_ST_st4_fsm_3;
            when ap_ST_st4_fsm_3 => 
                ap_NS_fsm <= ap_ST_st5_fsm_4;
            when ap_ST_st5_fsm_4 => 
                if ((ap_const_lv1_0 = tmp_8_fu_811_p2)) then
                    ap_NS_fsm <= ap_ST_st8_fsm_7;
                else
                    ap_NS_fsm <= ap_ST_st6_fsm_5;
                end if;
            when ap_ST_st6_fsm_5 => 
                ap_NS_fsm <= ap_ST_st7_fsm_6;
            when ap_ST_st7_fsm_6 => 
                ap_NS_fsm <= ap_ST_st8_fsm_7;
            when ap_ST_st8_fsm_7 => 
                ap_NS_fsm <= ap_ST_st9_fsm_8;
            when ap_ST_st9_fsm_8 => 
                ap_NS_fsm <= ap_ST_st10_fsm_9;
            when ap_ST_st10_fsm_9 => 
                if ((ap_const_lv1_0 = tmp_13_fu_1124_p2)) then
                    ap_NS_fsm <= ap_ST_st13_fsm_12;
                else
                    ap_NS_fsm <= ap_ST_st11_fsm_10;
                end if;
            when ap_ST_st11_fsm_10 => 
                ap_NS_fsm <= ap_ST_st12_fsm_11;
            when ap_ST_st12_fsm_11 => 
                ap_NS_fsm <= ap_ST_st13_fsm_12;
            when ap_ST_st13_fsm_12 => 
                ap_NS_fsm <= ap_ST_st14_fsm_13;
            when ap_ST_st14_fsm_13 => 
                ap_NS_fsm <= ap_ST_st1_fsm_0;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    AstimDelay_load_op_fu_491_p2 <= std_logic_vector(unsigned(AstimDelay) + unsigned(ap_const_lv32_1));
    AstimDelay_new_fu_1420_p3 <= 
        ap_const_lv32_0 when (or_cond1_fu_1409_p2(0) = '1') else 
        tmp_6_reg_1538;
    CircularBuffer_head_i_read_ass_1_fu_1110_p3 <= 
        ap_const_lv32_0 when (tmp_34_i1_fu_1104_p2(0) = '1') else 
        tmp_33_i1_fu_1099_p2;
    CircularBuffer_head_i_read_ass_fu_797_p3 <= 
        ap_const_lv32_0 when (tmp_34_i_fu_791_p2(0) = '1') else 
        tmp_33_i_fu_786_p2;
    CircularBuffer_int_30_sum_i1_fu_1071_p3 <= 
        tmp_29_i1_fu_1065_p2 when (tmp_i4_fu_1056_p2(0) = '1') else 
        recentABools_sum;
    CircularBuffer_int_30_sum_i_fu_758_p3 <= 
        tmp_29_i_fu_752_p2 when (tmp_i2_fu_743_p2(0) = '1') else 
        recentVBools_sum;
    CircularBuffer_len_read_assign_1_fu_778_p3 <= 
        ap_const_lv32_1E when (tmp_i2_fu_743_p2(0) = '1') else 
        CircularBuffer_len_read_assign_fu_772_p2;
    CircularBuffer_len_read_assign_2_fu_1085_p2 <= std_logic_vector(unsigned(recentABools_len) + unsigned(ap_const_lv32_1));
    CircularBuffer_len_read_assign_3_fu_1091_p3 <= 
        ap_const_lv32_1E when (tmp_i4_fu_1056_p2(0) = '1') else 
        CircularBuffer_len_read_assign_2_fu_1085_p2;
    CircularBuffer_len_read_assign_fu_772_p2 <= std_logic_vector(unsigned(recentVBools_len) + unsigned(ap_const_lv32_1));
    CircularBuffer_len_write_assig_1_fu_924_p2 <= std_logic_vector(unsigned(CircularBuffer_len_read_assign_1_reg_1616) + unsigned(ap_const_lv32_FFFFFFFE));
    CircularBuffer_len_write_assig_2_fu_1142_p2 <= std_logic_vector(unsigned(CircularBuffer_len_read_assign_3_fu_1091_p3) + unsigned(ap_const_lv32_FFFFFFFF));
    CircularBuffer_len_write_assig_3_fu_1249_p2 <= std_logic_vector(unsigned(CircularBuffer_len_read_assign_3_reg_1711) + unsigned(ap_const_lv32_FFFFFFFE));
    CircularBuffer_len_write_assig_fu_817_p2 <= std_logic_vector(unsigned(CircularBuffer_len_read_assign_1_fu_778_p3) + unsigned(ap_const_lv32_FFFFFFFF));
    CircularBuffer_sum_read_assign_1_fu_1079_p2 <= std_logic_vector(unsigned(CircularBuffer_int_30_sum_i1_fu_1071_p3) + unsigned(val_assign_2_fu_1045_p1));
    CircularBuffer_sum_read_assign_fu_766_p2 <= std_logic_vector(unsigned(CircularBuffer_int_30_sum_i_fu_758_p3) + unsigned(val_assign_1_fu_732_p1));
    CircularBuffer_sum_write_assig_1_fu_917_p2 <= std_logic_vector(unsigned(CircularBuffer_sum_write_assig_fu_909_p2) - unsigned(toReturn_i12_cast_fu_914_p1));
    CircularBuffer_sum_write_assig_2_fu_1234_p2 <= std_logic_vector(unsigned(CircularBuffer_sum_read_assign_1_reg_1705) - unsigned(toReturn_i25_cast_fu_1231_p1));
    CircularBuffer_sum_write_assig_3_fu_1242_p2 <= std_logic_vector(unsigned(CircularBuffer_sum_write_assig_2_fu_1234_p2) - unsigned(toReturn_i38_cast_fu_1239_p1));
    CircularBuffer_sum_write_assig_fu_909_p2 <= std_logic_vector(unsigned(CircularBuffer_sum_read_assign_reg_1610) - unsigned(toReturn_i_cast_fu_906_p1));
    VstimDelay_load_op_fu_505_p2 <= std_logic_vector(unsigned(VstimDelay) + unsigned(ap_const_lv32_1));
    VstimDelay_new_fu_1470_p3 <= 
        ap_const_lv32_0 when (or_cond3_fu_1458_p2(0) = '1') else 
        tmp_7_reg_1544;

    ap_done_assign_proc : process(ap_sig_cseq_ST_st14_fsm_13)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st14_fsm_13)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_sig_cseq_ST_st14_fsm_13)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st14_fsm_13)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

        ap_return <= std_logic_vector(resize(signed(toReturn_3_fu_1477_p3),16));


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_151_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
                ap_sig_151 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)));
    end process;


    ap_sig_176_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_176 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_187_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_187 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_200_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_200 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_210_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_210 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    ap_sig_236_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_236 <= (ap_const_lv1_1 = ap_CS_fsm(5 downto 5));
    end process;


    ap_sig_249_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_249 <= (ap_const_lv1_1 = ap_CS_fsm(6 downto 6));
    end process;


    ap_sig_260_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_260 <= (ap_const_lv1_1 = ap_CS_fsm(7 downto 7));
    end process;


    ap_sig_276_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_276 <= (ap_const_lv1_1 = ap_CS_fsm(8 downto 8));
    end process;


    ap_sig_286_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_286 <= (ap_const_lv1_1 = ap_CS_fsm(9 downto 9));
    end process;


    ap_sig_306_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_306 <= (ap_const_lv1_1 = ap_CS_fsm(10 downto 10));
    end process;


    ap_sig_31_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_31 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_319_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_319 <= (ap_const_lv1_1 = ap_CS_fsm(11 downto 11));
    end process;


    ap_sig_330_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_330 <= (ap_const_lv1_1 = ap_CS_fsm(12 downto 12));
    end process;


    ap_sig_365_assign_proc : process(last_sample_is_V_V_load_load_fu_962_p1, tmp_10_fu_944_p2)
    begin
                ap_sig_365 <= ((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1) and not((ap_const_lv1_0 = tmp_10_fu_944_p2)));
    end process;


    ap_sig_367_assign_proc : process(last_sample_is_V_V_load_load_fu_962_p1, tmp_10_fu_944_p2)
    begin
                ap_sig_367 <= (not((ap_const_lv1_0 = last_sample_is_V_V_load_load_fu_962_p1)) and (ap_const_lv1_0 = tmp_10_fu_944_p2));
    end process;


    ap_sig_404_assign_proc : process(last_sample_is_A_V_load_load_fu_1287_p1, tmp_16_fu_1269_p2, or_cond_fu_1303_p2)
    begin
                ap_sig_404 <= ((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1) and not((ap_const_lv1_0 = tmp_16_fu_1269_p2)) and not((ap_const_lv1_0 = or_cond_fu_1303_p2)));
    end process;


    ap_sig_408_assign_proc : process(last_sample_is_A_V_load_load_fu_1287_p1, tmp_16_fu_1269_p2, or_cond_fu_1303_p2)
    begin
                ap_sig_408 <= ((not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1)) and (ap_const_lv1_0 = tmp_16_fu_1269_p2)) or (not((ap_const_lv1_0 = last_sample_is_A_V_load_load_fu_1287_p1)) and (ap_const_lv1_0 = or_cond_fu_1303_p2)));
    end process;


    ap_sig_433_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_433 <= (ap_const_lv1_1 = ap_CS_fsm(13 downto 13));
    end process;


    ap_sig_cseq_ST_st10_fsm_9_assign_proc : process(ap_sig_286)
    begin
        if (ap_sig_286) then 
            ap_sig_cseq_ST_st10_fsm_9 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st10_fsm_9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st11_fsm_10_assign_proc : process(ap_sig_306)
    begin
        if (ap_sig_306) then 
            ap_sig_cseq_ST_st11_fsm_10 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st11_fsm_10 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st12_fsm_11_assign_proc : process(ap_sig_319)
    begin
        if (ap_sig_319) then 
            ap_sig_cseq_ST_st12_fsm_11 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st12_fsm_11 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st13_fsm_12_assign_proc : process(ap_sig_330)
    begin
        if (ap_sig_330) then 
            ap_sig_cseq_ST_st13_fsm_12 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st13_fsm_12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st14_fsm_13_assign_proc : process(ap_sig_433)
    begin
        if (ap_sig_433) then 
            ap_sig_cseq_ST_st14_fsm_13 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st14_fsm_13 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_31)
    begin
        if (ap_sig_31) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_176)
    begin
        if (ap_sig_176) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_187)
    begin
        if (ap_sig_187) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_200)
    begin
        if (ap_sig_200) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st5_fsm_4_assign_proc : process(ap_sig_210)
    begin
        if (ap_sig_210) then 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st6_fsm_5_assign_proc : process(ap_sig_236)
    begin
        if (ap_sig_236) then 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st7_fsm_6_assign_proc : process(ap_sig_249)
    begin
        if (ap_sig_249) then 
            ap_sig_cseq_ST_st7_fsm_6 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st7_fsm_6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st8_fsm_7_assign_proc : process(ap_sig_260)
    begin
        if (ap_sig_260) then 
            ap_sig_cseq_ST_st8_fsm_7 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st8_fsm_7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st9_fsm_8_assign_proc : process(ap_sig_276)
    begin
        if (ap_sig_276) then 
            ap_sig_cseq_ST_st9_fsm_8 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st9_fsm_8 <= ap_const_logic_0;
        end if; 
    end process;

    brmerge_fu_1349_p2 <= (tmp_21_not_fu_1337_p2 or last_sample_is_V_V_loc_2_not_fu_1343_p2);
    datapointA_1_fu_1017_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(datapointA_cast_fu_1003_p1));
        datapointA_cast_fu_1003_p1 <= std_logic_vector(resize(signed(datapointA_fu_996_p3),17));

    datapointA_fu_996_p3 <= 
        recentdatapoints_data_q0 when (tmp_i3_reg_1674(0) = '1') else 
        ap_const_lv16_0;
    datapointV_1_fu_674_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(datapointV_cast_fu_660_p1));
        datapointV_cast_fu_660_p1 <= std_logic_vector(resize(signed(datapointV_fu_652_p3),17));

    datapointV_fu_652_p3 <= 
        ap_const_lv16_0 when (tmp_i1_fu_647_p2(0) = '1') else 
        recentdatapoints_data_q0;
    extLd1_fu_749_p1 <= std_logic_vector(resize(unsigned(recentVBools_data_load_reg_1584),32));
    extLd2_fu_1062_p1 <= std_logic_vector(resize(unsigned(recentABools_data_load_reg_1700),32));
        extLd_fu_533_p1 <= std_logic_vector(resize(signed(recentdatapoints_data_q0),32));

    i_10_fu_1166_p3 <= 
        i_9_fu_1160_p2 when (tmp_28_fu_1152_p3(0) = '1') else 
        i_8_fu_1148_p2;
    i_11_fu_1179_p2 <= std_logic_vector(unsigned(CircularBuffer_head_i_read_ass_1_reg_1719) - unsigned(CircularBuffer_len_write_assig_2_reg_1729));
    i_12_fu_1191_p2 <= std_logic_vector(unsigned(i_11_fu_1179_p2) + unsigned(ap_const_lv32_1E));
    i_13_fu_1197_p3 <= 
        i_12_fu_1191_p2 when (tmp_29_fu_1183_p3(0) = '1') else 
        i_11_fu_1179_p2;
    i_1_fu_620_p2 <= std_logic_vector(unsigned(p_tmp_i_reg_1556) + unsigned(ap_const_lv32_13));
    i_2_fu_823_p2 <= std_logic_vector(unsigned(CircularBuffer_head_i_read_ass_reg_1624) - unsigned(CircularBuffer_len_read_assign_1_reg_1616));
    i_3_fu_835_p2 <= std_logic_vector(unsigned(i_2_fu_823_p2) + unsigned(ap_const_lv32_1E));
    i_4_fu_841_p3 <= 
        i_3_fu_835_p2 when (tmp_26_fu_827_p3(0) = '1') else 
        i_2_fu_823_p2;
    i_5_fu_854_p2 <= std_logic_vector(unsigned(CircularBuffer_head_i_read_ass_reg_1624) - unsigned(CircularBuffer_len_write_assig_reg_1634));
    i_6_fu_866_p2 <= std_logic_vector(unsigned(i_5_fu_854_p2) + unsigned(ap_const_lv32_1E));
    i_7_fu_872_p3 <= 
        i_6_fu_866_p2 when (tmp_27_fu_858_p3(0) = '1') else 
        i_5_fu_854_p2;
    i_8_fu_1148_p2 <= std_logic_vector(unsigned(CircularBuffer_head_i_read_ass_1_reg_1719) - unsigned(CircularBuffer_len_read_assign_3_reg_1711));
    i_9_fu_1160_p2 <= std_logic_vector(unsigned(i_8_fu_1148_p2) + unsigned(ap_const_lv32_1E));
    i_fu_607_p2 <= std_logic_vector(unsigned(p_tmp_i_reg_1556) + unsigned(ap_const_lv32_FFFFFFFF));
    last_sample_is_A_V_load_load_fu_1287_p1 <= last_sample_is_A_V;
    last_sample_is_V_V_load_load_fu_962_p1 <= last_sample_is_V_V;
    last_sample_is_V_V_loc_2_not_fu_1343_p2 <= (last_sample_is_V_V_loc_2_reg_358 xor ap_const_lv1_1);
    not_tmp_i_i1_fu_1215_p2 <= "0" when (CircularBuffer_len_read_assign_3_reg_1711 = ap_const_lv32_0) else "1";
    not_tmp_i_i2_fu_1210_p2 <= "0" when (CircularBuffer_len_write_assig_2_reg_1729 = ap_const_lv32_0) else "1";
    not_tmp_i_i4_fu_885_p2 <= "0" when (CircularBuffer_len_write_assig_reg_1634 = ap_const_lv32_0) else "1";
    not_tmp_i_i_fu_890_p2 <= "0" when (CircularBuffer_len_read_assign_1_reg_1616 = ap_const_lv32_0) else "1";
    or_cond1_fu_1409_p2 <= (tmp_21_fu_1403_p2 and tmp_22_reg_1772);
    or_cond3_fu_1458_p2 <= (tmp1_fu_1453_p2 and tmp_23_fu_1435_p2);
    or_cond_fu_1303_p2 <= (tmp_17_fu_1291_p2 and tmp_18_fu_1297_p2);
        p_1_cast_fu_1031_p1 <= std_logic_vector(resize(signed(p_1_fu_1023_p3),32));

    p_1_fu_1023_p3 <= 
        datapointA_1_fu_1017_p2 when (tmp_11_fu_1011_p2(0) = '1') else 
        datapointA_cast_fu_1003_p1;
    p_2_fu_1361_p3 <= 
        ap_const_lv13_1000 when (tmp_19_reg_409(0) = '1') else 
        ap_const_lv13_0;
        p_cast_fu_688_p1 <= std_logic_vector(resize(signed(p_s_fu_680_p3),32));

    p_i_fu_625_p3 <= 
        i_1_fu_620_p2 when (tmp_fu_612_p3(0) = '1') else 
        i_fu_607_p2;
    p_s_fu_680_p3 <= 
        datapointV_1_fu_674_p2 when (tmp_9_fu_668_p2(0) = '1') else 
        datapointV_cast_fu_660_p1;
    p_tmp_i_fu_587_p3 <= 
        ap_const_lv32_0 when (tmp_40_i_fu_581_p2(0) = '1') else 
        tmp_39_i_fu_576_p2;

    recentABools_data_address0_assign_proc : process(ap_sig_cseq_ST_st8_fsm_7, recentABools_data_addr_reg_1689, ap_sig_cseq_ST_st10_fsm_9, ap_sig_cseq_ST_st11_fsm_10, tmp_i4_10_fu_991_p1, tmp_28_i_i1_fu_1174_p1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9)) then 
            recentABools_data_address0 <= recentABools_data_addr_reg_1689;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10)) then 
            recentABools_data_address0 <= tmp_28_i_i1_fu_1174_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7)) then 
            recentABools_data_address0 <= tmp_i4_10_fu_991_p1(5 - 1 downto 0);
        else 
            recentABools_data_address0 <= "XXXXX";
        end if; 
    end process;

    recentABools_data_address1 <= tmp_28_i_i2_fu_1205_p1(5 - 1 downto 0);

    recentABools_data_ce0_assign_proc : process(ap_sig_cseq_ST_st8_fsm_7, ap_sig_cseq_ST_st10_fsm_9, ap_sig_cseq_ST_st11_fsm_10)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) or (ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9) or (ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10))) then 
            recentABools_data_ce0 <= ap_const_logic_1;
        else 
            recentABools_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    recentABools_data_ce1_assign_proc : process(ap_sig_cseq_ST_st11_fsm_10)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10)) then 
            recentABools_data_ce1 <= ap_const_logic_1;
        else 
            recentABools_data_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    recentABools_data_we0_assign_proc : process(ap_sig_cseq_ST_st10_fsm_9)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9))) then 
            recentABools_data_we0 <= ap_const_logic_1;
        else 
            recentABools_data_we0 <= ap_const_logic_0;
        end if; 
    end process;


    recentABools_len_new_phi_fu_388_p4_assign_proc : process(tmp_13_reg_1725, ap_sig_cseq_ST_st13_fsm_12, CircularBuffer_len_write_assig_3_fu_1249_p2, recentABools_len_new_reg_385)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = tmp_13_reg_1725)))) then 
            recentABools_len_new_phi_fu_388_p4 <= CircularBuffer_len_write_assig_3_fu_1249_p2;
        else 
            recentABools_len_new_phi_fu_388_p4 <= recentABools_len_new_reg_385;
        end if; 
    end process;


    recentVBools_data_address0_assign_proc : process(ap_sig_cseq_ST_st3_fsm_2, recentVBools_data_addr_reg_1573, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st6_fsm_5, tmp_i2_8_fu_642_p1, tmp_28_i_i_fu_849_p1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
            recentVBools_data_address0 <= recentVBools_data_addr_reg_1573;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5)) then 
            recentVBools_data_address0 <= tmp_28_i_i_fu_849_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
            recentVBools_data_address0 <= tmp_i2_8_fu_642_p1(5 - 1 downto 0);
        else 
            recentVBools_data_address0 <= "XXXXX";
        end if; 
    end process;

    recentVBools_data_address1 <= tmp_28_i_i9_fu_880_p1(5 - 1 downto 0);

    recentVBools_data_ce0_assign_proc : process(ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st6_fsm_5)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5))) then 
            recentVBools_data_ce0 <= ap_const_logic_1;
        else 
            recentVBools_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    recentVBools_data_ce1_assign_proc : process(ap_sig_cseq_ST_st6_fsm_5)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5)) then 
            recentVBools_data_ce1 <= ap_const_logic_1;
        else 
            recentVBools_data_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    recentVBools_data_we0_assign_proc : process(ap_sig_cseq_ST_st5_fsm_4)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4))) then 
            recentVBools_data_we0 <= ap_const_logic_1;
        else 
            recentVBools_data_we0 <= ap_const_logic_0;
        end if; 
    end process;


    recentVBools_len_new_phi_fu_320_p4_assign_proc : process(tmp_8_reg_1630, ap_sig_cseq_ST_st8_fsm_7, CircularBuffer_len_write_assig_1_fu_924_p2, recentVBools_len_new_reg_317)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = tmp_8_reg_1630)))) then 
            recentVBools_len_new_phi_fu_320_p4 <= CircularBuffer_len_write_assig_1_fu_924_p2;
        else 
            recentVBools_len_new_phi_fu_320_p4 <= recentVBools_len_new_reg_317;
        end if; 
    end process;


    recentdatapoints_data_address0_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, recentdatapoints_data_addr_reg_1533, ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7, tmp_i_7_fu_486_p1, tmp_41_i_fu_633_p1, tmp_i3_9_fu_983_p1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
            recentdatapoints_data_address0 <= recentdatapoints_data_addr_reg_1533;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7)) then 
            recentdatapoints_data_address0 <= tmp_i3_9_fu_983_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
            recentdatapoints_data_address0 <= tmp_41_i_fu_633_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) then 
            recentdatapoints_data_address0 <= tmp_i_7_fu_486_p1(5 - 1 downto 0);
        else 
            recentdatapoints_data_address0 <= "XXXXX";
        end if; 
    end process;


    recentdatapoints_data_ce0_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0, ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0))) or (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) or (ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
            recentdatapoints_data_ce0 <= ap_const_logic_1;
        else 
            recentdatapoints_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    recentdatapoints_data_we0_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1))) then 
            recentdatapoints_data_we0 <= ap_const_logic_1;
        else 
            recentdatapoints_data_we0 <= ap_const_logic_0;
        end if; 
    end process;

    recentdatapoints_len_load_op_fu_556_p2 <= std_logic_vector(unsigned(recentdatapoints_len) + unsigned(ap_const_lv32_1));
    recentdatapoints_sum_loc_i_fu_543_p3 <= 
        tmp_35_i_fu_537_p2 when (tmp_i_fu_523_p2(0) = '1') else 
        recentdatapoints_sum;
    reset_params_V_read_read_fu_180_p2 <= reset_params_V;
    sel_tmp1_fu_1375_p3 <= 
        p_2_fu_1361_p3 when (sel_tmp_fu_1369_p2(0) = '1') else 
        ap_const_lv13_0;
    sel_tmp2_fu_1389_p2 <= (last_sample_is_V_V_loc_2_reg_358 and tmp_21_not_not_fu_1383_p2);
    sel_tmp_fu_1369_p2 <= (brmerge_fu_1349_p2 and tmp_20_fu_1355_p2);

    sum_1_phi_fu_379_p4_assign_proc : process(tmp_13_reg_1725, ap_sig_cseq_ST_st13_fsm_12, CircularBuffer_sum_write_assig_3_fu_1242_p2, sum_1_reg_376)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and not((ap_const_lv1_0 = tmp_13_reg_1725)))) then 
            sum_1_phi_fu_379_p4 <= CircularBuffer_sum_write_assig_3_fu_1242_p2;
        else 
            sum_1_phi_fu_379_p4 <= sum_1_reg_376;
        end if; 
    end process;


    sum_phi_fu_311_p4_assign_proc : process(tmp_8_reg_1630, ap_sig_cseq_ST_st8_fsm_7, CircularBuffer_sum_write_assig_1_fu_917_p2, sum_reg_308)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) and not((ap_const_lv1_0 = tmp_8_reg_1630)))) then 
            sum_phi_fu_311_p4 <= CircularBuffer_sum_write_assig_1_fu_917_p2;
        else 
            sum_phi_fu_311_p4 <= sum_reg_308;
        end if; 
    end process;

    tmp1_fu_1453_p2 <= (tmp_24_fu_1441_p2 and tmp_25_reg_1777);
    tmp_10_fu_944_p2 <= "1" when (signed(sum_phi_fu_311_p4) > signed(tmp_2_fu_940_p1)) else "0";
    tmp_11_fu_1011_p2 <= "1" when (aflip = ap_const_lv8_FF) else "0";
    tmp_12_fu_1039_p2 <= "1" when (signed(p_1_cast_fu_1031_p1) > signed(a_thresh)) else "0";
    tmp_13_fu_1124_p2 <= "1" when (signed(CircularBuffer_len_read_assign_3_fu_1091_p3) > signed(ACaptureThresh_loc_reg_288)) else "0";
    tmp_14_fu_1255_p4 <= ACaptureThresh_loc_reg_288(31 downto 1);
        tmp_15_fu_1265_p1 <= std_logic_vector(resize(signed(tmp_14_fu_1255_p4),32));

    tmp_16_fu_1269_p2 <= "1" when (signed(sum_1_phi_fu_379_p4) > signed(tmp_15_fu_1265_p1)) else "0";
    tmp_17_fu_1291_p2 <= "1" when (signed(VbeatDelay_new_1_reg_326) > signed(VbeatFallDelay_new_1_reg_342)) else "0";
    tmp_18_fu_1297_p2 <= "1" when (signed(VbeatFallDelay_new_1_reg_342) > signed(ap_const_lv32_FA)) else "0";
    tmp_1_fu_930_p4 <= VCaptureThresh_loc_reg_298(31 downto 1);
    tmp_20_fu_1355_p2 <= "1" when (AbeatDelay_new_reg_394 = ap_const_lv32_0) else "0";
    tmp_21_fu_1403_p2 <= "1" when (signed(AbeatDelay_new_reg_394) > signed(ap_const_lv32_3E8)) else "0";
    tmp_21_not_fu_1337_p2 <= "0" when (VbeatDelay_new_1_reg_326 = ap_const_lv32_0) else "1";
    tmp_21_not_not_fu_1383_p2 <= (tmp_21_not_fu_1337_p2 xor ap_const_lv1_1);
    tmp_22_fu_1321_p2 <= "1" when (signed(tmp_6_reg_1538) > signed(ACaptureThresh_loc_reg_288)) else "0";
    tmp_23_fu_1435_p2 <= "1" when (signed(VbeatDelay_new_1_reg_326) > signed(AbeatDelay_new_reg_394)) else "0";
    tmp_24_fu_1441_p2 <= "1" when (signed(AbeatDelay_new_reg_394) > signed(ap_const_lv32_384)) else "0";
    tmp_25_fu_1326_p2 <= "1" when (signed(tmp_7_reg_1544) > signed(VCaptureThresh_loc_reg_298)) else "0";
    tmp_26_fu_827_p3 <= i_2_fu_823_p2(31 downto 31);
    tmp_27_fu_858_p3 <= i_5_fu_854_p2(31 downto 31);
    tmp_28_fu_1152_p3 <= i_8_fu_1148_p2(31 downto 31);
        tmp_28_i_i1_fu_1174_p1 <= std_logic_vector(resize(signed(i_10_fu_1166_p3),64));

        tmp_28_i_i2_fu_1205_p1 <= std_logic_vector(resize(signed(i_13_fu_1197_p3),64));

        tmp_28_i_i9_fu_880_p1 <= std_logic_vector(resize(signed(i_7_fu_872_p3),64));

        tmp_28_i_i_fu_849_p1 <= std_logic_vector(resize(signed(i_4_fu_841_p3),64));

    tmp_29_fu_1183_p3 <= i_11_fu_1179_p2(31 downto 31);
    tmp_29_i1_fu_1065_p2 <= std_logic_vector(unsigned(recentABools_sum) - unsigned(extLd2_fu_1062_p1));
    tmp_29_i_fu_752_p2 <= std_logic_vector(unsigned(recentVBools_sum) - unsigned(extLd1_fu_749_p1));
        tmp_2_fu_940_p1 <= std_logic_vector(resize(signed(tmp_1_fu_930_p4),32));

    tmp_33_i1_fu_1099_p2 <= std_logic_vector(unsigned(recentABools_head_i) + unsigned(ap_const_lv32_1));
    tmp_33_i_fu_786_p2 <= std_logic_vector(unsigned(recentVBools_head_i) + unsigned(ap_const_lv32_1));
    tmp_34_i1_fu_1104_p2 <= "1" when (tmp_33_i1_fu_1099_p2 = ap_const_lv32_1E) else "0";
    tmp_34_i_fu_791_p2 <= "1" when (tmp_33_i_fu_786_p2 = ap_const_lv32_1E) else "0";
    tmp_35_i_fu_537_p2 <= std_logic_vector(unsigned(recentdatapoints_sum) - unsigned(extLd_fu_533_p1));
    tmp_37_i_fu_551_p2 <= std_logic_vector(unsigned(recentdatapoints_sum_loc_i_fu_543_p3) + unsigned(val_assign_reg_1513));
    tmp_38_i_fu_562_p3 <= 
        ap_const_lv32_14 when (tmp_i_fu_523_p2(0) = '1') else 
        recentdatapoints_len_load_op_fu_556_p2;
    tmp_39_i_fu_576_p2 <= std_logic_vector(unsigned(recentdatapoints_head_i) + unsigned(ap_const_lv32_1));
    tmp_3_fu_706_p2 <= std_logic_vector(unsigned(AbeatDelay) + unsigned(ap_const_lv32_1));
    tmp_40_i_fu_581_p2 <= "1" when (tmp_39_i_fu_576_p2 = ap_const_lv32_14) else "0";
        tmp_41_i_fu_633_p1 <= std_logic_vector(resize(signed(p_i_fu_625_p3),64));

    tmp_4_fu_716_p2 <= std_logic_vector(unsigned(VbeatDelay) + unsigned(ap_const_lv32_1));
    tmp_5_fu_726_p2 <= std_logic_vector(unsigned(VbeatFallDelay) + unsigned(ap_const_lv32_1));
    tmp_6_fu_497_p3 <= 
        ap_const_lv32_1 when (reset_A_V(0) = '1') else 
        AstimDelay_load_op_fu_491_p2;
    tmp_7_fu_511_p3 <= 
        ap_const_lv32_1 when (reset_V_V(0) = '1') else 
        VstimDelay_load_op_fu_505_p2;
    tmp_8_fu_811_p2 <= "1" when (signed(CircularBuffer_len_read_assign_1_fu_778_p3) > signed(VCaptureThresh_loc_reg_298)) else "0";
    tmp_9_fu_668_p2 <= "1" when (vflip = ap_const_lv8_FF) else "0";
    tmp_fu_612_p3 <= i_fu_607_p2(31 downto 31);
    tmp_i1_fu_647_p2 <= "1" when (tmp_38_i_reg_1550 = ap_const_lv32_0) else "0";
        tmp_i2_8_fu_642_p1 <= std_logic_vector(resize(signed(recentVBools_head_i),64));

    tmp_i2_fu_743_p2 <= "1" when (recentVBools_len = ap_const_lv32_1E) else "0";
        tmp_i3_9_fu_983_p1 <= std_logic_vector(resize(signed(p_tmp_i_reg_1556),64));

    tmp_i3_fu_978_p2 <= "1" when (tmp_38_i_reg_1550 = ap_const_lv32_14) else "0";
        tmp_i4_10_fu_991_p1 <= std_logic_vector(resize(signed(recentABools_head_i),64));

    tmp_i4_fu_1056_p2 <= "1" when (recentABools_len = ap_const_lv32_1E) else "0";
        tmp_i_7_fu_486_p1 <= std_logic_vector(resize(signed(recentdatapoints_head_i),64));

    tmp_i_fu_523_p2 <= "1" when (recentdatapoints_len = ap_const_lv32_14) else "0";
    tmp_s_fu_696_p2 <= "1" when (signed(p_cast_fu_688_p1) > signed(v_thresh)) else "0";
    toReturn_1_fu_1395_p3 <= 
        ap_const_lv13_F0 when (sel_tmp2_fu_1389_p2(0) = '1') else 
        sel_tmp1_fu_1375_p3;
    toReturn_2_fu_1427_p3 <= 
        toReturn_fu_1414_p2 when (or_cond1_fu_1409_p2(0) = '1') else 
        toReturn_1_fu_1395_p3;
    toReturn_3_fu_1477_p3 <= 
        toReturn_4_fu_1464_p2 when (or_cond3_fu_1458_p2(0) = '1') else 
        toReturn_2_fu_1427_p3;
    toReturn_4_fu_1464_p2 <= (toReturn_2_fu_1427_p3 or ap_const_lv13_F);
    toReturn_5_fu_895_p2 <= (recentVBools_data_q0 and not_tmp_i_i_fu_890_p2);
    toReturn_6_fu_901_p2 <= (recentVBools_data_q1 and not_tmp_i_i4_reg_1650);
    toReturn_7_fu_1220_p2 <= (recentABools_data_q0 and not_tmp_i_i1_fu_1215_p2);
    toReturn_8_fu_1226_p2 <= (recentABools_data_q1 and not_tmp_i_i2_reg_1745);
    toReturn_fu_1414_p2 <= (toReturn_1_fu_1395_p3 or ap_const_lv13_F00);
    toReturn_i12_cast_fu_914_p1 <= std_logic_vector(resize(unsigned(toReturn_6_reg_1660),32));
    toReturn_i25_cast_fu_1231_p1 <= std_logic_vector(resize(unsigned(toReturn_7_reg_1750),32));
    toReturn_i38_cast_fu_1239_p1 <= std_logic_vector(resize(unsigned(toReturn_8_reg_1755),32));
    toReturn_i_cast_fu_906_p1 <= std_logic_vector(resize(unsigned(toReturn_5_reg_1655),32));
    val_assign_1_fu_732_p1 <= std_logic_vector(resize(unsigned(tmp_s_reg_1578),32));
    val_assign_2_fu_1045_p1 <= std_logic_vector(resize(unsigned(tmp_12_reg_1694),32));
        val_assign_fu_426_p1 <= std_logic_vector(resize(signed(data),32));

end behav;
